### ISSUE TITLE
Explore the idea of testing integrations at the PR level

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1005]
If we get a PR of the integrations repo, and build a custom version of the production image of the registry, including PR's code into it, we could deploy that registry including that integrations PR into the tests.

- Understand the build process of the registry image
- Copy integrations dir into a well-known directory under the https://github.com/elastic/package-registry / https://github.com/elastic/package-storage structure
- Build the image, use it in tests

We could do the same for the package-registry itself: test PRs to the registry. It would be the same process described above, without adding the integrations.

cc/ @exekias

**Comment by kseniia-kolpakova** [comment]
This issue is research only

**Comment by mdelapenya** [comment]
Package registry is not built for ARM, so this could be a limitation for this issue, as we would need to run our own version of the package registry in ARM workers
