### ISSUE TITLE
Revert uninstall tests once flakyness is under control

### ISSUE THREAD

**Issue by michalpristas** [elastic/e2e-testing#1022]
Add removed step from this PR https://github.com/elastic/e2e-testing/pull/1017 back when we have a way of reflecting changes more quickly

**Comment by kseniia-kolpakova** [comment]
Related to https://github.com/elastic/e2e-testing/issues/895

**Comment by adam-stokes** [comment]
I think this is resolved already, @mdelapenya can you confirm?
