### ISSUE TITLE
Kibana master and 7.x is not able to start

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1048]
The kibana instance for the Fleet profile is not able to start, dying with: 

>[fleet_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT][92ea04a8160be3afdd0c164e27df2e4a9ff6ade7d45878c0e094081f4fc541e1][2021-04-19T05:43:07.295Z] {"type":"log","@timestamp":"2021-04-19T05:43:07+00:00","tags":["fatal","root"],"pid":937,"message":"ValidationError: [config validation of [xpack.fleet].agents.kibana]: definition for this key is missing\n    at ObjectType.validate (/usr/share/kibana/node_modules/@kbn/config-schema/target/types/type.js:51:19)\n    at ConfigService.validateAtPath (/usr/share/kibana/node_modules/@kbn/config/target/config_service.js:170:23)\n    at MapSubscriber.project (/usr/share/kibana/node_modules/@kbn/config/target/config_service.js:177:166)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at ReplaySubject._subscribe (/usr/share/kibana/node_modules/rxjs/internal/ReplaySubject.js:80:28)\n    at ReplaySubject.Observable._trySubscribe (/usr/share/kibana/node_modules/rxjs/internal/Observable.js:44:25)\n    at ReplaySubject.Subject._trySubscribe (/usr/share/kibana/node_modules/rxjs/internal/Subject.js:102:51)\n    at ReplaySubject.Observable.subscribe (/usr/share/kibana/node_modules/rxjs/internal/Observable.js:30:22)\n    at MapSubscriber.shareReplayOperation (/usr/share/kibana/node_modules/rxjs/internal/operators/shareReplay.js:48:32)\n    at Observable.subscribe (/usr/share/kibana/node_modules/rxjs/internal/Observable.js:25:31)\n    at MapOperator.call (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:32:23) {\n  cause: SchemaTypeError: definition for this key is missing\n      at ObjectType.onError (/usr/share/kibana/node_modules/@kbn/config-schema/target/types/type.js:76:20)\n      at type.<anonymous> (/usr/share/kibana/node_modules/@kbn/config-schema/target/types/type.js:41:53)\n      at finish (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:529:50)\n      at type._validate (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:618:24)\n      at type._base (/usr/share/kibana/node_modules/joi/lib/types/object/index.js:212:45)\n      at type._validate (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:614:37)\n      at type._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:674:29)\n      at module.exports.internals.Any.root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:146:23)\n      at ObjectType.validate (/usr/share/kibana/node_modules/@kbn/config-schema/target/types/type.js:46:72)\n      at ConfigService.validateAtPath (/usr/share/kibana/node_modules/@kbn/config/target/config_service.js:170:23)\n      at MapSubscriber.project (/usr/share/kibana/node_modules/@kbn/config/target/config_service.js:177:166)\n      at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:49:35)\n      at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n      at DistinctUntilChangedSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n      at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n      at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26) {\n    cause: undefined,\n    path: [ 'agents', 'kibana' ]\n  }\n}"}
[fleet_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT][92ea04a8160be3afdd0c164e27df2e4a9ff6ade7d45878c0e094081f4fc541e1][2021-04-19T05:43:07.305Z] 
[fleet_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT][92ea04a8160be3afdd0c164e27df2e4a9ff6ade7d45878c0e094081f4fc541e1][2021-04-19T05:43:07.305Z]  FATAL  Error: [config validation of [xpack.fleet].agents.kibana]: definition for this key is missing
[fleet_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT][92ea04a8160be3afdd0c164e27df2e4a9ff6ade7d45878c0e094081f4fc541e1][2021-04-19T05:43:07.305Z] 

Kibana config can be found here: https://github.com/elastic/e2e-testing/blob/master/cli/config/compose/profiles/fleet/configurations/kibana.config.yml

Relates to https://github.com/elastic/kibana/issues/97412

**Comment by ruflin** [comment]
@mdelapenya Check the fix that was made in https://github.com/elastic/elastic-package/pull/319 It should also solve this one here hopefully.

**Comment by mdelapenya** [comment]
Fixed in #1008
