### ISSUE TITLE
Generate the feature files that are related to the beats integration modules

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#106]
We have fixed feature files for apache, mysql, redis and vsphere, where we manually update the supported versions as examples in the gherkin table. To keep this in sync with the real supported versions, which are defined in the Beats repo, in the supported-versions.yml file for the module.

We could generate the files at build time using templates: one for modules without variants (i.e. apache) and one for modules with variants (i.e. mysql). The feature files are exactly equals but the module name and the examples.

```diff
-@apache
+@redis
-Feature: As a Metricbeat developer I want to check that the Apache module works as expected
+Feature: As a Metricbeat developer I want to check that the Redis module works as expected

Scenario Outline: Check module is sending metrics to Elasticsearch without errors
-  Given Apache "<apache_version>" is running for metricbeat
+  Given Redis "<redis_version>" is running for metricbeat
-    And metricbeat is installed and configured for Apache module
+    And metricbeat is installed and configured for Redis module
    And metricbeat waits "20" seconds for the service
  When metricbeat runs for "20" seconds 
-  Then there are "Apache" events in the index
+  Then there are "Redis" events in the index
    And there are no errors in the index
Examples:
-| apache_version |
+| redis_version |
-| 2.4.12         |
-| 2.4.20         |
+| 3.2.12         |
+| 4.0.11         |
+| 5.0.5          |
```

I think we can commit the templates and ignore the feature files, which will provide an automated manner of testing both new and existing integrations in an automated manner.

@jsoriano what are your thoughts about this?

**Comment by jsoriano** [comment]
Yeah, I think we should do something to take supported versions into account. Tests should use the files of the metricbeat version being tested.

Regarding the variants, we should think that actually any variable can be present there. At the moment we have MySQL's `MYSQL_VARIANT` and Ceph's `CEPH_CODENAME` (thought this is a different thing). +1 to having a common template plus specific template overrides for these special cases by now. Later we can see if we can have something more general.

**Comment by mdelapenya** [comment]
Let's close this one, as we simplified the feature file using examples per integration
