### ISSUE TITLE
In-correct command for downloading sync-integration dependency is provided in notes for setting up e2e-testing repo

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/e2e-testing#1081]
Currently, command mentioned in notes at location: https://github.com/elastic/e2e-testing/tree/master/e2e/_suites/fleet on Step 4, related to downloading of sync-integration dependency is in-correct and causing some sort of confusions and misleading for users who are new to Docker tool and setting up e2e-testing repo on Docker. 

Reference Screenshot:
![image](https://user-images.githubusercontent.com/72375798/115834384-cd9ef980-a432-11eb-8949-548e1e2ddc8b.png)

So, expected command need to be updated is follows:
make -C cli sync-integrations

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @EricDavisX
