### ISSUE TITLE
Proper notes instructions are missing for downloading dependencies on 'e2e-testing/e2e/_suites/fleet/' Repo page

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/e2e-testing#1082]
At Step 4 on [e2e testing Fleet](https://github.com/elastic/e2e-testing/tree/master/e2e/_suites/fleet) repo page, an instruction to install dependency without any clear instructions is provided as below:

- Install dependencies.
     - Install Go: https://golang.org/doc/install (The CI uses GVM)

It could be better if a note is provided like: 'Please follow instructions provided here as CI uses GVM' instead of '(The CI uses GVM)' content in below screenshot:

![image](https://user-images.githubusercontent.com/72375798/115836179-cb3d9f00-a434-11eb-92d2-2cc319a0f028.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @EricDavisX
