### ISSUE TITLE
Maintain our own images for centos and debian

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1089]
Because of ARM support, we cannot simply pull the images from Docker hub on ARM machines, as those images where built only for AMD.

We'd need to maintain our own Dockerfiles and build them in both AMD and ARM.

cc/ @elastic/observablt-robots

**Comment by v1v** [comment]
Do you mean the images that we build in the `beats-ci`? or the ones the unified release process build? If the latter then the `-platform` should be there IIRC. Otherwise, we might need to discuss with the beats team as they own their build system

**Comment by mdelapenya** [comment]
In this particular case, I mean the centos/debian images we maintain for running the elastic agent in our tests.

I'll send a PR for that (hopefully reusable into a shareable step)

**Comment by mdelapenya** [comment]
More specifically:

- https://github.com/elastic/e2e-testing/blob/master/cli/config/compose/services/centos-systemd/docker-compose.yml#L4
- https://github.com/elastic/e2e-testing/blob/master/cli/config/compose/services/debian-systemd/docker-compose.yml#L4

Because they were built on AMD, they do not work when the tests are run on ARM.
