### ISSUE TITLE
[k8s Autodiscover] SUpport running test suite agains Beats PRs or local filesystem

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1106]
The same way we do for other test suites (fleet and metricbeat) we'd like to test beats' PRs/branches or binaries created from the local build in Beats.

For that reason, we'd need to detect if the build was triggered by a PR/branch from Beats, or using local file system, and load the Docker image for:
- metricbeat
- filebeat
- heartbeat
in Kind's runtime, using `kind load image-archive $theFile.tar`

cc/ @jsoriano

**Comment by mdelapenya** [comment]
This is currently impacting Beats PRs/branches

**Comment by jsoriano** [comment]
Related to https://github.com/elastic/beats/issues/25307
