### ISSUE TITLE
Improve resiliency of testing suit

### ISSUE THREAD

**Issue by jalvz** [elastic/e2e-testing#1108]
`make test` should be as independent as possible and pass/fail on its own terms, not in function of machine state, other commands, etc.

- Pull fresh Docker images without needed a separate command.
- Clean up .op folder after each run (to avoid keeping garbage around eg. when switching branches)
- Get docker-compose files for metricbeat directly from the network instead of forcing a whole Beats checkout

**Comment by mdelapenya** [comment]
I think this feature it's almost implemented:
- [x] compose files are refreshed on each test suite
- [x] each test suite is pulling its own set of images (configurable with the SKIP_PULL variable)
- [ ] metricbeat's compose files is not implemented yet.

**Comment by mdelapenya** [comment]
For the latest, I think it would come with a a big refactor:

- the feature file does not make a differentiation on x-pack Vs non-x-pack modules (well, it's done at the annotation/tag level, but that value is not passed from the feature file to the Go code). Therefore, we cannot dynamically fetch the compose file for the integration from the Beats repo directly
- we could add the xpack field to the outline examples in the feature file, and pass it to the scenario Go code. Then we could download the compose file (and related files, after sanitising them) and use it to spin up the integration service

**Comment by mdelapenya** [comment]
I think we can close this one, as metricbeat test suite was removed in favour of the fleet one

Please reopen if needed
