### ISSUE TITLE
elastic agent json log changes name from `elastic-agent-json.log` to `elastic-agent-json.log-{date}`

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1127]
@mdelapenya elastic agent json log changes name from `elastic-agent-json.log` to `elastic-agent-json.log-{date}` 
are any changes necessary in a test suite?

_Originally posted by @michalpristas in https://github.com/elastic/beats/issues/25464#issuecomment-832000812_

**Comment by kseniia-kolpakova** [comment]
Related to https://github.com/elastic/e2e-testing/issues/742

**Comment by mdelapenya** [comment]
We are not affected by this, as we are simply running `docker log` for the running container. I'd close this in favour of #742, as it's the one that could be affected by the aforementioned change
