### ISSUE TITLE
k8s-autodiscover test suite is failing for builds triggered by Beats

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1165]
Example: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/870/pipeline

The test error seems caused by this log:
>[2021-05-14T14:08:57.981Z] time="2021-05-14T14:08:57Z" level=debug msg="Error checking if /tmp/test-489066118/events contains kubernetes.service.name:redis: opening /tmp/test-489066118/events: open /tmp/test-489066118/events: no such file or directory"

cc/ @jsoriano

**Comment by jsoriano** [comment]
@mdelapenya can the flaky test be skipped by now?

**Comment by jsoriano** [comment]
Ok, better if there is already a fix :slightly_smiling_face: Thanks!
