### ISSUE TITLE
Spread tests on CI by feature file instead of by tags

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1191]
We are currently selecting scenarios by TAGS, which makes it difficult to add one new scenario with a new tag into the CI, being necessary to add a new test suite. You can check #1186 as an example: a new scenario in a new feature file was added **2 months ago**, and it was not ran until past week because of that.

Because we are grouping scenarios by feature files, we could move to that approach: instead of passing the `-t` flag to godog, we could pass the `-f` one, which adds all scenarios in a file.

**Comment by cachedout** [comment]
@mdelapenya Just preparing for the iteration planning today. Could you please update this issue to describe any remaining work to be done or close it and open a specific issue which describes that work? That will help us get a bit more organized for the next couple of weeks. Thanks so much!
