### ISSUE TITLE
[CI] E2E tests with custom Kibana can be run once at a time, only

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1210]
I tried to run to different builds at the same time, and the second one must wait for the previous one to finish.

cc/ @elastic/observablt-robots

**Comment by cachedout** [comment]
Sorry for the accidental closure there. Mis-click. :)

**Comment by kuisathaverat** [comment]
Not relevant in isolate environments that do not share the Elactic Stack to run.
