### ISSUE TITLE
Document how to write a very basic e2e test in the repository

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1237]
We'd like to speed up the process of starting with the project and writing a test scenario that passes.

**Comment by cachedout** [comment]
Hi @mdelapenya . I think this may now be a duplicate of https://github.com/elastic/observability-robots/issues/608

Do you want to keep them both open or just go ahead and close this one?

**Comment by mdelapenya** [comment]
I'd keep both, as the robots one is related to the E2E strategy/vision, and this one is related to specifically this test framework
