### ISSUE TITLE
Reduce the number of documents that are verified in the stand-alone mode

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1247]
cc/ @EricDavisX 

We are currently waiting for 50 docs in the index, and it takes +4 min to reach that number:

> [2021-06-09T13:00:15.261Z] time="2021-06-09T13:00:14Z" level=info msg="Hits number satisfied" currentHits=50 desiredHits=50 elapsedTime=4m34.393628738s retries=57

OTOH, it takes ~30secs to have 25 docs in the index:

> [2021-06-09T12:55:58.421Z] time="2021-06-09T12:55:58Z" level=warning msg="Waiting for more hits in the index" currentHits=0 desiredHits=50 elapsedTime=17.776235468s index=logs-elastic_agent-default retry=7

> [2021-06-09T12:56:01.635Z] time="2021-06-09T12:56:01Z" level=warning msg="Waiting for more hits in the index" currentHits=24 desiredHits=50 elapsedTime=21.333274089s index=logs-elastic_agent-default retry=8

> [2021-06-09T12:56:08.697Z] time="2021-06-09T12:56:08Z" level=warning msg="Waiting for more hits in the index" currentHits=25 desiredHits=50 elapsedTime=28.175342997s index=logs-elastic_agent-default retry=9

What do you think about reducing that amount of docs? We will be cutting down almost 3 mins to the stand-alone parallel branch in the build.

## Screenshots
This is a capture of the APM traces for the span representing the step `there is new data in the index from agent`:
<img width="1787" alt="Screenshot 2021-06-10 at 10 25 58" src="https://user-images.githubusercontent.com/951580/121491517-50294b80-c9d6-11eb-8bba-252a5215b48c.png">

**Comment by EricDavisX** [comment]
I agree - I think we'd be much better off waiting for just 20 or 25.  With what I now know, it seems a very easy choice to make this change

**Comment by mdelapenya** [comment]
> @IgorGuz2000 do you want to do this smaller change for us? If so feel free to assign and do it up!

@IgorGuz2000, both @adam-stokes and I we'll be glad to guide you during the review :)

**Comment by EricDavisX** [comment]
@IgorGuz2000 tagging you

**Comment by adam-stokes** [comment]
This is done #1275
