### ISSUE TITLE
Elastic-agent install command fails on Debian + ARM in an inconsistent manner

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1271]
The elastic-agent `install` command fails in an inconsistence manner when running on a Debian + ARM Docker image. With inconsistence we mean that we use the `install` command for all scenarios, and it only fails for the `Deploying the debian agent`

You can find an example CI build [here](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/995/pipeline)

We do not see errors at the PR level because we selected centos as the only image to be run on PRs. For that reason we observe this error on the nightly builds for [Fleet tests](https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-fleet-daily-mbp/) 

> We offer a **private** Docker image for Debian with multi-platform support (AMD and ARM): https://container-library.elastic.co/r/observability-ci/debian-systemd, so to reproduce this, you should be able to run the tests on an ARM box, or in the CI

#### Log Error
>[2021-06-17T09:02:59.239Z] time="2021-06-17T09:02:58Z" level=error msg="Error executing command" args="[exec -u root -i fleet_elastic-agent_1 /elastic-agent/elastic-agent install -e -v --force --insecure --enrollment-token=TU5BMUdYb0JLcTh2emV0ZFd4OUs6S09EZTJuWklUeGViNnpRZEszTTM1QQ== --url http://fleet-server:8220]" baseDir=. command=docker error="exit status 1" stderr="2021-06-17T09:02:51.807Z\tINFO\t[composable]\tcomposable/controller.go:46\tEXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production\n2021-06-17T09:02:51.911Z\tINFO\t[composable.providers.docker]\tdocker/docker.go:43\tDocker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n2021-06-17T09:02:52.012Z\tINFO\tcapabilities/capabilities.go:59\tcapabilities file not found in /elastic-agent/capabilities.yml\n2021-06-17T09:02:58.464Z\tINFO\t[composable]\tcomposable/controller.go:46\tEXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production\n2021-06-17T09:02:58.566Z\tINFO\t[composable.providers.docker]\tdocker/docker.go:43\tDocker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n2021-06-17T09:02:58.667Z\tINFO\tcapabilities/capabilities.go:59\tcapabilities file not found in /elastic-agent/capabilities.yml\nError: failed to start service (elastic-agent): exit status 5\n"

cc/ @michalpristas @blakerouse @EricDavisX @elastic/observablt-robots

**Comment by cachedout** [comment]
@mdelapenya We have this in our current iteration but we don't have an owner assigned. Was this something you were going to take on and we should assign to you or should we find an owner for it?

**Comment by mdelapenya** [comment]
Let me grab it and will work on it, as we are trying to trace back the existing errors on CI for Fleet, thanks for the reminder

**Comment by mdelapenya** [comment]
I'd say we need to investigate it more. I've checked the master branch and cannot see this error in any of today's builds for the master branch, although I do see them for the 7.13.x branch (https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.13.x/92/pipeline) and in yesterday's builds: 
**Failed builds**:
- https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1050/tests
- https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1054/tests
- https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1055/tests

**Comment by cachedout** [comment]
@mdelapenya Thanks for the update!

**Comment by mdelapenya** [comment]
More on this.

The test scenario " Deploying the debian agent" of the "Fleet Mode Agent" feature file is failing in an inconsistent manner: sometimes fails, sometimes not. Here we paste the links to the CI builds including the most relevant logs that we found:

1. When installing the agent **always for the first test scenario of the test suite** running on ARM + Debian, the install commands exits with **5**, which means input/output error. The log relates to Docker.

>[2021-07-20T07:18:43.492Z] time="2021-07-20T07:18:43Z" level=error msg="Error executing command" args="[exec -u root -i fleet_elastic-agent_1 /elastic-agent/elastic-agent install -e -v --force --insecure --enrollment-token=R3p6SHdub0JHTDUtUWlCRDM4QTQ6Xy1NOUF1X1lRUkdNaEtMcElDWUdUdw== --url http://fleet-server:8220]" baseDir=. command=docker error="exit status 1" stderr="2021-07-20T07:18:41.924Z\tINFO\t[composable]\tcomposable/controller.go:46\tEXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production\n2021-07-20T07:18:42.027Z\tINFO\t[composable.providers.docker]\tdocker/docker.go:43\tDocker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n2021-07-20T07:18:42.127Z\tINFO\tcapabilities/capabilities.go:59\tcapabilities file not found in /elastic-agent/capabilities.yml\n2021-07-20T07:18:43.067Z\tINFO\t[composable]\tcomposable/controller.go:46\tEXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production\n2021-07-20T07:18:43.169Z\tINFO\t[composable.providers.docker]\tdocker/docker.go:43\tDocker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n2021-07-20T07:18:43.270Z\tINFO\tcapabilities/capabilities.go:59\tcapabilities file not found in /elastic-agent/capabilities.yml\nError: failed to start service (elastic-agent): exit status 5\n"

2. When tearing down the test scenario in the tearDown phase of the tests (happens always, granted by the test runner), we try to uninstall the agent, and the command exits with **126**, which means [the command is found but it's not executable](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html#:~:text=If%20a%20command%20is%20found,status%20is%20greater%20than%20zero.).

>[2021-07-20T07:18:43.993Z] time="2021-07-20T07:18:43Z" level=error msg="Error executing command" args="[exec -u root -i fleet_elastic-agent_1 elastic-agent uninstall -f]" baseDir=. command=docker error="exit status 126" stderr=
[2021-07-20T07:18:43.993Z] time="2021-07-20T07:18:43Z" level=warning msg="Could not uninstall the agent after the scenario: Failed to uninstall the agent with subcommand: exit status 126"


## CI links

### 7.13.x builds
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.13.x/118/pipeline. One error, same log.
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.13.x/117/tests. Two errors, same log.
- ✅ https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.13.x/115/tests. No errors

### 7.14.x builds:
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.14.x/99/tests. the Debian + ARM failure appears in one single test failure. Same log error.
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.14.x/95/tests. Two errors, same log.

### 7.x builds:
- ✅ https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.x/709/tests. No errors
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.x/708/tests. One error, same log.
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.x/707/tests. Two errors, same log.


### master
- ✅ https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1150/pipeline. No errors.
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1148/tests. One error.
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1146/tests. One error.
- 🔴 https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1145/tests. Two errors.
- ✅ https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1143/pipeline. No errors

**Comment by mdelapenya** [comment]
After #1341, we are using a fixed ARM flavour as CI worker, and right after that we started to see success for the ARM+Debian tests in a consistent manner.

We also created a PR (#1369) to run the ARM+Debian tests more frequently, every 2 hours, and the results are consistently successful.

I'd say this flakiness could have been driven by the differences between docker engines in the underlying CI ARM worker (Ubuntu, Centos), and now that it's fixed, I'd close this issue as not reproducible any more.

**Comment by cachedout** [comment]
> I'd close this issue as not reproducible any more.

+1 for closing it. We can always re-open it later if needed.

**Comment by mdelapenya** [comment]
Closing as described in #1369

**Comment by mdelapenya** [comment]
Dammit: at the moment we closed this.... https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1204/tests

<img width="1785" alt="Screenshot 2021-07-28 at 18 52 20" src="https://user-images.githubusercontent.com/951580/127363972-10d15f8a-acc1-499c-85df-c9257fdf9a74.png">

@cachedout is this something that the flakey-test-analyser should have captured?

**Comment by cachedout** [comment]
> is this something that the flakey-test-analyser should have captured?

The analyzer only runs once a night so it won't pick up something that just happened today.
