### ISSUE TITLE
[ci] update ci to support running e2e on windows

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#1308]
A job needs to be created in order to support running our e2e tests against a windows and mac host

- [x] Create pipeline similar to node apm so that we can boot up 2 instances together
- [x] Expose the IP address of the linux instance housing the deployed stack
- [x] Use the IP from the deployed stack on the second VM (windows in this case) to connect to the stack
- [ ] Add to pipeline to execute correct command for connecting to remote env
- [ ] Execute remote provider for testing a local agent
- [ ] Report results properly
- [ ] Create MacOS variant for CI (requires ephemeral macos instances)

**Comment by cachedout** [comment]
@adam-stokes I don't see any recent movement on this so I'm going to move it back into the planned column for this iteration.

**Comment by adam-stokes** [comment]
@cachedout Yea sorry, the last thing to do is talk with infra to figure out why the machines aren't able to communicate with each other within the same region

**Comment by cachedout** [comment]
@adam-stokes Thanks. Do you have a contact over there on that issue? You could have @nkammah help you find somebody if you aren't able to find the appropriate person.
