### ISSUE TITLE
Optional configuration are not working when runing E2E tests

### ISSUE THREAD

**Issue by IgorGuz2000** [elastic/e2e-testing#1311]
I try to execute test with Optional config for running with different STACK_VERSION and also with PROVIDER=remote to use cloud deployment servers, non of them worked.

from e2e/_suites/fleet OP_LOG_LEVEL=DEBUG DEV=true godog -t '@system_integration'

**Comment by adam-stokes** [comment]
@IgorGuz2000 Do you mind posting what you run in the terminal?

**Comment by adam-stokes** [comment]
I think you want this instead:

```
cd e2e/_suites/fleet
DEVELOPER_MODE=true go test -v --godog.tags='@system_integration'
```

**Comment by IgorGuz2000** [comment]
When I run with this command it fails:
[run.txt](https://github.com/elastic/e2e-testing/files/6811906/run.txt)

**Comment by adam-stokes** [comment]
Sorry the default timeout for go test is 10 minutes, run it like this:

```
cd e2e/_suites/fleet
DEVELOPER_MODE=true go test -timeout 30m -v --godog.tags='@system_integration'
```

**Comment by EricDavisX** [comment]
@adam-stokes I had a task of mine to follow up, unless someone gets to it sooner - do we have the above doc'ed in the repo?  the --godog.tags usage seems new to me.  we can group a bunch of updates together later when we make time, just asking.

**Comment by adam-stokes** [comment]
> @adam-stokes I had a task of mine to follow up, unless someone gets to it sooner - do we have the above doc'ed in the repo? the --godog.tags usage seems new to me. we can group a bunch of updates together later when we make time, just asking.

Hey @EricDavisX , we do have these items documented at https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/fleet/README.md, the`--godog.tags` usage was introduced when we switched over to using `go test`

**Comment by adam-stokes** [comment]
We've made a bunch of improvements to documentation that should help guide developers in using the correct invocations, including what environment variables should/can be set in the README.  Going to close this out as updates have been made since then to help improve this workflow
