### ISSUE TITLE
Remove systemd from the centos/debian images

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1340]
After our daily, we suggested removing the systemd layer in the base images used for testing Fleet. We think this layer could be causing the flakiness described in #1271.

- remove the creation of the systemd-based images for Debian and Centos
- replace systemd-based images with the official ones.

cc/ @elastic/observablt-robots @EricDavisX

**Comment by mdelapenya** [comment]
After replacing the Base Docker images with the official centos/debian images, we see that any execution of the "elastic-agent install" command fails with the following error:

Test error:
>ERRO[2021-07-21T08:18:02+02:00] Error executing command                       args="[exec -u root -i fleet_elastic-agent_1 /elastic-agent/elastic-agent install -e -v --force --insecure --enrollment-token=VnlhMngzb0JXWi0td0Nkb2c4MHY6TXBjaUpzYjRUbU9pRjR6SE5NS2UyZw== --url http://fleet-server:8220]" baseDir=. command=docker error="exit status 1"

Agent error:
>2021-07-21T06:18:02.105Z\tINFO\t[composable.providers.docker]\tdocker/docker.go:43\tDocker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2021-07-21T06:18:02.206Z\tINFO\tcapabilities/capabilities.go:59\tcapabilities file not found in /elastic-agent/capabilities.yml
2021-07-21T06:18:02.694Z\tINFO\t[composable.providers.docker]\tdocker/docker.go:43\tDocker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2021-07-21T06:18:02.795Z\tINFO\tcapabilities/capabilities.go:59\tcapabilities file not found in /elastic-agent/capabilities.yml\nError: failed to start service (elastic-agent): \"service\" failed: exec: \"service\": executable file not found in $PATH"

It seems that the agent needs the "service" command to be present in the target machine, which makes it difficult to run in a plain container without an init system (such as systemd). We'd like to know from @elastic/apm-agent-devs if `systemd` is a strong requirement for the agent to be present in the target machine (vm, container).

**Comment by michalpristas** [comment]
when installing an agent we are creating a new service using `github.com/kardianos/service` 
if this fails installation fails. 
in case service manager is missing enroll+run may be considered but this will result in agent not running after host reboot unless some startup script is used.

**Comment by mdelapenya** [comment]
We could move to `enroll + run` in all scenarios, but there is one that verifies that the agent is persisted across reboots (expects a service is created). Everything depends on the level of testing we want to provide: is it enough to test the enroll + run command? Do we want to cover service-based commands too?

**Comment by michalpristas** [comment]
ideal situation is where we have both scenarios covered. 
leaving install unused means that we are not testing use case which will be used most frequently by user.

**Comment by cachedout** [comment]
Hi @michalpristas 

If I understand this correctly, `install` should not be used on systems without init systems. 

If that's true, is it also true that `install` should _not_ be recommended for use inside containers, which typically do not have full-fledged init systems?

**Comment by michalpristas** [comment]
yes correct. for container use case we have a special `container` subcommand. this provides some config options using ENV Vars and under the hood is also enroll+run

**Comment by cachedout** [comment]
Ah, OK. That makes perfect sense. Thank you for the clarification!

**Comment by mdelapenya** [comment]
@michalpristas thanks for clarifying. I think we need to sit down and sync up about what to do with the current test strategy for commands. Will engage with the team to do so

**Comment by blakerouse** [comment]
There is 3 installation scenarios for the Elastic Agent:

1. `install` command - This our preferred installation path on full machines (aka. not a container). This provides all features of the Elastic Agent including self-upgrading from Kibana.
2. `beats/elastic-agent` container - This is the official Elastic Agent container, it runs its own `container` subcommand internally and sets up the Elastic Agent correctly for running inside of a container. If you are running inside of a container then this should be the image that is used. This does not allow the ability for self-upgrading from Kibana. It requires a new container image to be used to upgrade (the state directory can be placed on a volume so upgrade will use the same information from the previous version).
3. `deb/rpm` installation - This is our alternative installation path on full machines. This does not allow the ability for self-upgrading from Kibana. It requires a new deb/rpm to be installed to upgrade.

**Comment by kuisathaverat** [comment]
`install`  and `deb/rpm` are designed to run on a host (not a container) so we should test them in a host (VM), thus we have to instrument/mock stuff in a container that is not a real host and do no test what we want to test.

**Comment by cachedout** [comment]
@blakerouse I take from that then that if you want an agent in a custom container, the sanctioned way will be to use multi-stage builds? It sounds like building a container from scratch with the agent isn't supported. Is that correct?

**Comment by mdelapenya** [comment]
To simulate the installation of the agent binaries (rpm, deb and tar) in Centos/Debian machines, because we are running the tests using Docker containers, we decided to use plain [Centos](https://github.com/elastic/e2e-testing/blob/master/.ci/docker/centos-systemd/Dockerfile) and [Debian](https://github.com/elastic/e2e-testing/blob/master/.ci/docker/debian-systemd/Dockerfile) images installing systemd in the base container, and we agreed to use containers for the sake of speed in development.

For that reason, we are always using the `elastic-agent install` command in the tests.

Besides that, we have two modes in the tests: stand-alone mode and fleet mode. We run stand-alone mode tests using the "official" Docker image for the agent. For the rests (and majority) of the tests we use the plain Centos/Debian images with systemd images copying the binaries into them, and finally running install command.

**Comment by blakerouse** [comment]
@cachedout Correct building from scratch is not something we support the file structure is important so it needs to be the official elastic-agent container. I am trying to think of a use-case on why you would need a custom elastic-agent container and I cannot think of one.

**Comment by blakerouse** [comment]
> To simulate the installation of the agent binaries (rpm, deb and tar) in Centos/Debian machines, because we are running the tests using Docker containers, we decided to use plain [Centos](https://github.com/elastic/e2e-testing/blob/master/.ci/docker/centos-systemd/Dockerfile) and [Debian](https://github.com/elastic/e2e-testing/blob/master/.ci/docker/debian-systemd/Dockerfile) images installing systemd in the base container, and we agreed to use containers for the sake of speed in development.
> 
> For that reason, we are always using the `elastic-agent install` command in the tests.
> 
> Besides that, we have two modes in the tests: stand-alone mode and fleet mode. We run stand-alone mode tests using the "official" Docker image for the agent. For the rests (and majority) of the tests we use the plain Centos/Debian images with systemd images copying the binaries into them, and finally running install command.

This seems like there is a large gap in coverage here then. Because the official container can running in either standalone mode or Fleet mode. Standalone vs Fleet mode doesn't matter the installation method. The 3 installation methods I listed above work for all modes.

**Comment by mdelapenya** [comment]
@EricDavisX maybe we can sync up and reevaluate what we all agreed in the past, which was to focus in the binaries installation (tar, deb, rpm) for the fleet-mode, even though the Docker image supports that.

I think we are still in a good position to turn gears and take the right approach, one that needs a strong alignment with the dev team.

**Comment by EricDavisX** [comment]
I'm learning a lot here, thank you everyone for the time and discourse. 

@blakerouse about your note on the 3 supported mechanisms.  It raises a concern I have a concern about the Agent design.  It seems to preclude Agent's use from a user with existing containers in their network.  Is that right? 
 I don't see what our supported method is for someone to deploy Agent as such.  If this is the design, so be it, but it can be clarified and documented, somewhat urgently.

Back to testing:
Further to your note on testing, we do have significant gaps, I've brought them up to the best of my ability, but perhaps we should find a new way to communicate current state, next steps (urgent) and moderate term coverage needs / goals.  We have tickets ready for deeper / additional support when engineers are ready, and we are prioritizing the list routinely and adding in new tickets for support.  All feedback is welcome.

A few specific notes I can chime in with:
I believe we do have coverage for enroll command, with the rpm/deb tests (noted below).  We also have coverage the install command and coverage over the Elastic Agent Container.  That's all 3 methods right?  It's pretty good, for having such a fast moving project!  Let's celebrate that.  :)

Here is the enroll command test: 
https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/fleet/features/fleet_mode_agent.feature#L22
 @mdelapenya if I'm misunderstanding that it actually performs an 'install' still, I'd like to be corrected and we can put a ticket in for this on the 'urgent' side.  Previously, before the 'install' command existed, we started writing the tests and everything was with 'enroll'.  We changed most tests, for the sake of time, to 'install' when the command came to life, just for some background.

Additionally, the open question as to how much of retesting do we need to do with various variables in the system for install 1) enroll vs install, 2)  container usage vs standard host vm, 3) deb vs tar package, and more.  For one thing we need to know the technical / architectural reasons how the risks manifest with the different variables, so we know how to test, and then we need to figure out a way to run the same basic test in X number of ways and configurations with possible different results based on configuration at hand.  That complex test running desire isn't new, and it isn't solved now I admit.  The current plan was just to repeat the tests with some minimal human readable feature files as needed, copy and paste saves us (for now).  it is manageable, but sub-optimal.  I'm open to any discussion!  I had started a ticket previously:
https://github.com/elastic/e2e-testing/issues/252 and I have updated it with current state of play.  It would be great to have he test running as more versatile with all the options / params we have, but it hasn't been calm enough to prioritize that (from my side at least).

Finally, we are close to having support for standard linux (and windows!) vms as the install base for the Agent during a given scenario.  I submit we can table some discussion based on the fact that the coverage is imminently improving.  The question of permutations and what constitutes 'urgent' vs 'moderate' need is one we can have.  
 https://github.com/elastic/e2e-testing/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3ATeam%3AAgent
 here is the list of open 'Team:Agent' labeled issues, there are a few more from 'Fleet' side, too.  It looks like the list is ripe for prioritization, the 'priority:urgent' label is applied only to the systemd tickets that started this discussion. I'll copy this to a new issue for subsequent review / comment:

Manu to your question, sounds good - let's pivot.  Let's chat soon, I'm hoping the linux vms (we were so existed about Windows support!) will be exactly what we need here.  And we can add Windows too, lol.  Thank you again all.

**Comment by blakerouse** [comment]
> I'm learning a lot here, thank you everyone for the time and discourse.
> 
> @blakerouse about your note on the 3 supported mechanisms. It raises a concern I have a concern about the Agent design. It seems to preclude Agent's use from a user with existing containers in their network. Is that right?
> I don't see what our supported method is for someone to deploy Agent as such. If this is the design, so be it, but it can be clarified and documented, somewhat urgently.

I am some what confused on your statement here. Containers are made to be isolated from each other, joining them together (Elastic Agent + some app) is a bad idea and defeats the purpose of a container.

Containers normally stay isolated from each other and they share information either through API's or the filesystem. So in the case of Elastic Agent you would want to mount a shared volume between an application and the Elastic Agent container.

> 
> Back to testing:
> Further to your note on testing, we do have significant gaps, I've brought them up to the best of my ability, but perhaps we should find a new way to communicate current state, next steps (urgent) and moderate term coverage needs / goals. We have tickets ready for deeper / additional support when engineers are ready, and we are prioritizing the list routinely and adding in new tickets for support. All feedback is welcome.
> 
> A few specific notes I can chime in with:
> I believe we do have coverage for enroll command, with the rpm/deb tests (noted below). We also have coverage the install command and coverage over the Elastic Agent Container. That's all 3 methods right? It's pretty good, for having such a fast moving project! Let's celebrate that. :)

I think this is missing the testing of the container in the case with Fleet. Unless that is also covered, would be great if it is.

**Comment by EricDavisX** [comment]
@mdelapenya Blake helped resolve concerns I had (due to a lack of deeper knowledge in Docker usage) and I think we can move forward indeed.  Removing systemd layer sounds right, and we can prioritize the Elastic Agent Docker Container in Fleet mode usage, as this is actually the exact usage of our Cloud product, so coverage there is key.  If we want to pull data from the existing manifests stored in Beats, they are here: https://github.com/elastic/beats/tree/master/deploy/kubernetes/elastic-agent-managed
and we have supporting docs imminently coming, I can link you separately.

I'm still reviewing the manifest files and figuring out how it would be used in our tests.

**Comment by mdelapenya** [comment]
@EricDavisX if we prioritise the Docker Container usage, how would the different installers be tested? At this moment of the test project, I have certain rate of trust in the tests for the different installers (RPM, DEB, TAR).

**Comment by EricDavisX** [comment]
@mdelapenya when you say a 'certain rate of trust' do you mean actually not a lot or that you DO have enough trust for now?  I am not confident in them myself after this discussion, particularly.  I'm nervous that we got creative and made them work, but that it is not a wise thing to do to a Docker container.  : /  I admit that I'd rather let you and Blake confer and decide the course, we can pull in Ruflin, or Andres for his guidance too, if it helps (as PH is out)?

My proposal is not necessarily to prioritize the Docker Container usage, but rather just let both of the Docker Container scenarios and the ephemeral workers usage basically be equal in priority.   I do see the implication you note that we won't be able to run the RPM, DEB, TAR tests from local usage, but maybe making a developer commit and letting CI run isn't such a bad compromise, and we can increase the amount of coverage in the Docker Container (stand-alone mode) tests.

**Comment by EricDavisX** [comment]
I'm going to send a note out to the team and PM.  We'd like to open the discussion to more people and gather some stats, too.  Do we have Telemetry on the most common usage of Agents, and/or the most common downloaded type of artifact?  Even without that data, I think the architectural pros and cons can be discussed and laid out and we can weigh the cost of change vs the pros + cons.

**Comment by EricDavisX** [comment]
Good discussion came via email, but no clear decision.  During the Agent team meeting today we concluded we would like to move forward with removing systemd layer and switch over to using the worker hosts in linux form, while maintaining the Elastic Agent container for docker tests (locally where desired).  @mdelapenya 

logistically, we can hold off on merging until we have a PR poised to add in the linux host tests.  we could add that work to the running PR if you agreed, too.

**Comment by cachedout** [comment]
>  switch over to using the worker hosts in linux form

@EricDavisX Could you please clarify what you mean by this? It sounds like you're saying that a layer needs to be added in the E2E test suite which can run tests on Linux VMs instead of containers but perhaps I am not getting the full context.

**Comment by mdelapenya** [comment]
This has been implemented after the move to VMs
