### ISSUE TITLE
Tar installer for mac is not starting/stopping the agent

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1347]
Our current implementation of the TAR installer for Mac makes use of `launchctl` and `start/stop` subcommands.

### Steps to reproduce

1. Make sure Fleet server is exposing the 8220 port
```shell 
vim ~/.op/compose/profiles/fleet/docker-compose.yml
# add the port definition for fleet-server
```

2. Make sure localhost reaches fleet server:
```shell
sudo echo "127.0.0.1         fleet-server" >> /etc/hosts
```

3. Start Fleet:
```shell
docker-compose -f ~/.op/compose/profiles/fleet/docker-compose.yml up -d
```

4. Download the agent
```shell
mkdir -p /tmp/agent
cd /tmp/agent
curl https://snapshots.elastic.co/8.0.0-1e9bea0f/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz -o elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz
tar -xvf elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz
mv elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64 elastic-agent
```

5. Get an enrollment token from Fleet UI: browse http://localhost:5601, log in, and get a token from Fleet app.

6. Install the agent using token:
```shell
sudo ./elastic-agent/elastic-agent install -e -v --force --insecure --enrollment-token=THE_TOKEN --url http://localhost:8220
```
 
7. Check agent has been installed in as a system Daemon:
```shell
ls -l /Library/LaunchDaemons/co.elastic.elastic-agent.plist
```

### Observations (from our current code base)
1. It's not possible to stop the agent with `launchctl stop elastic-agent`. I still see processes using `ps aux | grep elastic`
2. It's not possible to load the agent with `launchctl load elastic-agent`, same for unload
```shell
sudo launchctl load elastic-agent
/private/tmp/agent/elastic-agent/NOTICE.txt: Invalid path
/private/tmp/agent/elastic-agent/.build_hash.txt: Invalid path
/private/tmp/agent/elastic-agent/LICENSE.txt: Invalid path
/private/tmp/agent/elastic-agent/.elastic-agent.active.commit: Invalid path
/private/tmp/agent/elastic-agent/elastic-agent: Invalid path
/private/tmp/agent/elastic-agent/elastic-agent.yml: Invalid path
/private/tmp/agent/elastic-agent/README.md: Invalid path
/private/tmp/agent/elastic-agent/fleet.yml: Invalid path
/private/tmp/agent/elastic-agent/fleet.yml.lock: Invalid path
/private/tmp/agent/elastic-agent/data: Path not searched for services
/private/tmp/agent/elastic-agent/elastic-agent.reference.yml: Invalid path
Load failed: 133: Multiple errors were returned; see stderr
```

**Comment by adam-stokes** [comment]
Speaking with @blakerouse the correct invocation should be:

```
sudo launchctl load /Library/LaunchDaemons/co.elastic.elastic-agent.plist
```

Will test this out and report back, @mdelapenya is also testing this as well

**Comment by mdelapenya** [comment]
Running
```
sudo launchctl unload /Library/LaunchDaemons/co.elastic.elastic-agent.plist
```
Stops the agent in my machine, causing the agent is offline in Fleet UI. The opposite command:

```
sudo launchctl load /Library/LaunchDaemons/co.elastic.elastic-agent.plist
```
brings it back.

Will close this issue then. Thanks for the investigation, is it documented? I was not able to find any of it

**Comment by adam-stokes** [comment]
> Will close this issue then. Thanks for the investigation, is it documented? I was not able to find any of it

We should file a bug in their repo to get it documented
