### ISSUE TITLE
Check if the beat version snapshot contains a git commit

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1405]
I think we need to improve the automated bump with removing the calculation of the BeatVersionBase, which comes including the hash:

```golang
v, err := utils.GetElasticArtifactVersion(BeatVersionBase)
if err != nil {
	log.WithFields(log.Fields{
		"error":   err,
		"version": BeatVersionBase,
	}).Fatal("Failed to get Beat base version, aborting")
}
BeatVersionBase = v
```
A possible change could be to carry the fallback version between checks, replacing the `log.Fatal` with `log.Warn`:
```golang
v, err := utils.GetElasticArtifactVersion(BeatVersionBase)
if err != nil {
	log.WithFields(log.Fields{
		"error":   err,
		"version": BeatVersionBase,
	}).Warn("Failed to get Beat base version, aborting")
} else {
	BeatVersionBase = v
}
```

@adam-stokes wdyt?

_Originally posted by @mdelapenya in https://github.com/elastic/e2e-testing/issues/1391#issuecomment-888032893_

**Comment by mdelapenya** [comment]
After thinking about it, simply checking if the beat_version contains a git commit, reusing and building on top of what we already have for checking if a string is a git sha, we can verify if a version contains the sha (i.e. 8.0.0-abcdef-SNAPSHOT).

Then, we will be able to automatically merge the automated PRs from the bump-version

**Comment by mdelapenya** [comment]
Reopening because it's not fully complete: when downloading the elastic-agent (and any product) from `https://artifacts-api.elastic.co/v1/search/%s/%s?x-elastic-no-kpi=true` the binary is not found.

We need a way to get the download URL for the git-hashed version

**Comment by mdelapenya** [comment]
> Reopening because it's not fully complete: when downloading the elastic-agent (and any product) from `https://artifacts-api.elastic.co/v1/search/%s/%s?x-elastic-no-kpi=true` the binary is not found.
> 
> We need a way to get the download URL for the git-hashed version

We have solved it with #1406, but it's not enough: each time we use the common.BeatVersion variable, we are exposed to the issue of appending the git sha, creating paths that don't exist

**Comment by adam-stokes** [comment]
Just for my clarification, did this problem start happening after we implemented the automated bump-version functionality?

**Comment by mdelapenya** [comment]
Yes, it's not happening on master yet, as we are not merging the automated PRs
