### ISSUE TITLE
Add ability for test to inspect various error sources for if errors happened during run (docker console logs, or error streams, ES docs)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#141]
In working with the team on https://github.com/elastic/e2e-testing/pull/140/files
 - I realized the value of making sure nothing was showing us errors in the logs before we call a test passed.  

This relates to the Ingest Manager test suite and the Elastic-Agent docker container particularly.

I assume the steps would be something like:
- stream logs from docker container to a file as well as stdout (if needed?)
- when test needs to assert (usually at the end of a test case) we can exemplify / facilitate a grep thru the logs in that file against a given token, like 'ERROR:' and return success if not found
 - recommend making the grep case insensitive in case 'error' or 'Error' is seen as well.

**Comment by EricDavisX** [comment]
@michalpristas to divide and conquer more of the automation work, can you own this one particular?

**Comment by kuisathaverat** [comment]
resolved at https://github.com/elastic/e2e-testing/pull/3285
