### ISSUE TITLE
e2e-testing support to run Fleet Server repo CI tests during PR submission

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#1411]
See https://github.com/elastic/fleet-server/issues/77 for details of the request / need.  This ticket is for any work on e2e-testing side to support this.  Theoretically that ticket will collect steps / knowledge from the team about how to build Fleet Server and then include that build into an Elastic Agent artifact to be then consumed in the scenarios, and we'll implement changes here and there as needed.

The need came about When Agent shifted to use Fleet server and the new repo was instantiated.

The intention is to make use of the available existing tests for Agent, which make use of Fleet server component:
- [ ] details
- [ ] more details
- [ ] even more...

The ci hook will run a desired set of e2e-testing scenarios like what we have done for Agent and Kibana.  Reference this groovy file for info:
https://github.com/mdelapenya/beats/blob/921a3d52e60db04e0c92712203f097157f290265/.ci/packaging.groovy

**Comment by kuisathaverat** [comment]
done
