### ISSUE TITLE
Increase the number of retained builds

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1449]
The project only keeps the last 20 builds, and we'd need to retain a bigger number: 100? Because the main pipeline is a used as a helper, used as downstream for multiple sources (Beats PR/merges, nightly builds), in one day we loose the entire history.

**Comment by cachedout** [comment]
@mdelapenya We've had this task sitting in the ad-hoc in-progress column for a week. Is there a PR up for this or are you planning to put one up shortly? If it's not actually being worked on right now, let's move it back to the backlog to keep things tidy. :)
