### ISSUE TITLE
Refine Fleet-mode BDD steps

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#146]
We have a feature file with the steps. Let's revisit them checking its validity

**Comment by EricDavisX** [comment]
I'm evaluating the [fleet_mode_agent.feature](https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/ingest-manager/features/fleet_mode_agent.feature) file.  comparing against stand-alone mode feature file.  it looks pretty good, only needed a few updates.  I added 3 new scenarios at the same time.  yay.

**Comment by EricDavisX** [comment]
we decided to keep the PR open until we finish prior immediate tasks, but the work is done.  closing this as fixed
