### ISSUE TITLE
Step definitions need to be reworded to support multiple os/installtype matrix

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#1511]
Currently, the steps are a bit limited to just installtype and docker images as the foundation for running the tests. Now that we support Windows (and macOS as a result) we should update the step definitions to allow us to define those matrixes a bit better.

**Comment by cachedout** [comment]
We haven't had any activity here since this was moved from the backlog at the end of August. I am re-adding it to the backlog until we have a clearer idea of the work to be done here and the time it's going to take to complete it.

**Comment by cachedout** [comment]
@adam-stokes Could we please get a status on this issue? We've had it labeled as a high-impact and high-priority issue for two months but there hasn't been any movement on it. Is this blocked by something or do we need to find additional resources to handle this? If this is indeed labeled correctly, we need to find a path forward on this. Thanks!

**Comment by adam-stokes** [comment]
Yea this is blocked by https://github.com/elastic/e2e-testing/pull/1740# once we get pure VM testing in the pipelines we can work to make sure the tests run as intended within that environment

**Comment by cachedout** [comment]
Hi @adam-stokes 

Just checking in here. Now that #1740 is merged, is this unblocked?

**Comment by adam-stokes** [comment]
Hi @cachedout This is now unblocked

**Comment by mdelapenya** [comment]
I'd say this has been accomplished with the VM support
