### ISSUE TITLE
Auto-enroll agent option need to be added to the E2E testing 

### ISSUE THREAD

**Issue by IgorGuz2000** [elastic/e2e-testing#1512]
Auto-enroll agent option need to be added to the E2E testing. 
We need to add "--delay-enroll" option to agent deploy. This option is required to test Auto-enroll option when enrolling to the fleet are delayed until the agent host is restarted

**Comment by kuisathaverat** [comment]
duplicated https://github.com/elastic/e2e-testing/issues/1499
