### ISSUE TITLE
Agent upgrade test is failing

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1544]
The upgrade agent scenario is failing in a consisten manner since past Sep 2nd:

- Affected branches: master, 7.x, 7.15.x and 7.14.x

Test Scenario:
```gherkin
Scenario Outline: Upgrading the installed <os> agent
  Given a "<os>" agent "stale" is deployed to Fleet with "tar" installer
    And certs are installed
    And the "elastic-agent" process is "restarted" on the host
  When agent is upgraded to version "latest"
  Then agent is in version "latest"

@debian
Examples: Debian
| os     |
| debian |
```

From the spec we get the reproduction steps, and the tests:

1. Prepare environment: https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/fleet/README.md#running-the-tests
1. Run the upgrade test:

``` 
TAGS="fleet_mode_agent && nightly"  TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true ELASTIC_APM_ACTIVE=false make -C e2e/_suites/fleet functional-test
```

**Comment by mdelapenya** [comment]
I noticed that the stale version is stuck to 7.13-SNAPSHOT. Because we leverage the Elastic artifacts endpoint, old versions are disappearing: only current and last two versions are present in there.

I've run the tests with current state of the project (stale: 7.13) and the tests fail. Updating to 7.14-snapshot now it works.

@michalpristas what is the expected version to be used as stale? Is it correct to use (current - 1) or (current - 2) ??

**Comment by andresrc** [comment]
If the stale version is the version we are upgrading from, should not we use actual release versions and not snapshots? Is it possible to do so?

**Comment by EricDavisX** [comment]
I think reason we went with this is not technical, but strategical...  

If we implement using only 'shipped' releases for this test, it won't find bugs before we release.  Going back to the original feature / test design, there are 2 'halves' of the upgrade testing, the old agent upgrade to new agent tests 1/2 of it, and we never implemented the best approximation of the 2nd half which would be the current agent 'upgrading' to its same version (different code paths on Agent side).  So, using snapshots was to ensure we were covering what we could, of the current releasing code base before it ships.

**Comment by EricDavisX** [comment]
I am still thinking on this further about if we are best served by having different versions for different branches to get maximum coverage from what we've implemented.  We can probably survive just fine with this scheme so long as we keep updating the 'stale' version when we branch.  Thanks Manu for doing it and confirming it in the first place!

**Comment by mdelapenya** [comment]
@EricDavisX I think we can automate the bump with https://github.com/elastic/e2e-testing/blob/master/.ci/bump-stack-version.sh, per maintenance branch.

**Comment by michalpristas** [comment]
`current - 1` as stale should be fine
