### ISSUE TITLE
Quesion: to the team about Upgrade test that is commented out

### ISSUE THREAD

**Issue by IgorGuz2000** [elastic/e2e-testing#1582]
Ho we should handle the upgrade stale version. Right now we have the each branch have different stale version hard coded, which is hard to maintain, because you have to update stale version every time we have a new branch created. And each branch would have a different version to go against.
Any suggestions how to handle this better?
Maybe we should pull branch version and then select previous version

**Comment by mdelapenya** [comment]
After https://github.com/elastic/e2e-testing/pull/2354, I think we can close this one
