### ISSUE TITLE
use a more performant logger

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#1589]
I happened to come across https://github.com/uber-go/zap and more specifically: https://github.com/uber-go/zap#performance

It seems we can gain a bit more performance by switching from logrus to zap (both structured loggers). This seems like an easy win and not difficult to migrate our existing logging over to

**Comment by mdelapenya** [comment]
Yes! I had in mind having our own log package, so that we decouple all calls to it, simplifying refactors like the one proposed here.

**Comment by kuisathaverat** [comment]
there are no enough log messages to impact more than a few seconds per test, we will use ZAP in other projects.
