### ISSUE TITLE
Define feature-file scenarios for Agent & Endpoint deploy smoke & regression tests

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#160]
I'm going to add a few steps to a new file so we can track the work and maybe help pull in more resources to move it faster!

**Comment by EricDavisX** [comment]
first pr is here for this:
https://github.com/elastic/e2e-testing/pull/161
@mdelapenya fyi.

**Comment by EricDavisX** [comment]
@nnamdifrankie do you want to help push this into existence with us?!

**Comment by nnamdifrankie** [comment]
@EricDavisX sure are we just writing the feature files or also implementing the steps too?

**Comment by mdelapenya** [comment]
@nnamdifrankie we usually work in two iterations: first we define the BDD scenarios, and we iterate through them until we are satisfied:
- they hide implementation details
- they define in a high level of abstraction the purpose of the tests
- they follow a proper BDD sequence for Given/When/Then

Then we start another issue for the implementation details

**Comment by EricDavisX** [comment]
I have a new PR for the Endpoint side feature file:
https://github.com/elastic/e2e-testing/pull/195

If anyone wants to work with me on the Go implementation details to have a glorious end to end test for this (that will be run nightly and as part of Agent CI shortly)

**Comment by EricDavisX** [comment]
we got the first set of tests merged!  check master: https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/ingest-manager/features/agent_endpoint_integration.feature

For a snapshot-in-time, below are what landed.  A good follow up is what else do you want to urgently test that would make up 'first-order' tests we can't live without?  Hopefully the below is enough to get started and help us build it out.

`
@deploy-endpoint-with-agent
Scenario: Adding the Endpoint Integration to an Agent makes the host to show in Security App
  Given a "centos" agent is deployed to Fleet
    And the agent is listed in Fleet as "online"
  When the "Elastic Endpoint" integration is "added" in the policy
  Then the "Elastic Endpoint" datasource is shown in the policy as added
    And the host name is shown in the Administration view in the Security App as "online"
    
@endpoint-policy-check
Scenario: Deploying an Endpoint makes policies to appear in the Security App
  When an Endpoint is successfully deployed with a "centos" Agent
  Then the policy response will be shown in the Security App

@set-policy-and-check-changes
Scenario: Changing an Agent policy is reflected in the Security App
  Given an Endpoint is successfully deployed with a "centos" Agent
  When the policy is updated to have "malware" in "detect" mode
  Then the policy will reflect the change in the Security App

@deploy-endpoint-then-unenroll-agent
Scenario: Un-enrolling Elastic Agent stops Elastic Endpoint
  Given an Endpoint is successfully deployed with a "centos" Agent
  When the agent is un-enrolled
  Then the agent is listed in Fleet as "inactive"
    And the host name is not shown in the Administration view in the Security App
    And the "elastic-endpoint" process is in the "stopped" state on the host

@deploy-endpoint-then-remove-it-from-policy
Scenario: Removing Endpoint from Agent policy stops the connected Endpoint
  Given an Endpoint is successfully deployed with a "centos" Agent
  When the "Elastic Endpoint" integration is "removed" in the policy
  Then the agent is listed in Fleet as "online"
    But the host name is not shown in the Administration view in the Security App
    And the "elastic-endpoint" process is in the "stopped" state on the host`

**Comment by mdelapenya** [comment]
Hey @EricDavisX I think we can remove this one, as the endpoint feature file is merged and passing. Feel free to close it if so, thanks!

**Comment by EricDavisX** [comment]
Manu, hi - I was only leaving this open so that @nnamdifrankie @kevinlog @charlie-pichette @ferullo  had an open link to the repo and progress.  We still have only bare minimum tests for this... not sure if the team wants to leave it open or evaluate and log new specific tickets for the work which can be prioritized.

**Comment by mdelapenya** [comment]
Closing, as this test suite is implemented
