### ISSUE TITLE
Provide support for define output in BDD scenario 

### ISSUE THREAD

**Issue by ChrsMark** [elastic/e2e-testing#1655]
It would be nice if we have a way to provide multiple outputs' support so as people that create scenarios can just define where the suite should check for events. Example:

```
Scenario: Logs collection from running pod
  Given "elastic-agent" is running with "logs generic"
   When "a pod" is deployed
   Then "elastic-agent" collects events with "kubernetes.pod.name:a-pod" found in "es index a"
```

cc: @mdelapenya

**Comment by mdelapenya** [comment]
@adam-stokes after @ChrsMark's comment in https://github.com/elastic/e2e-testing/pull/2230#issuecomment-1067882411, I think we should prioritise this one. I triaged the issue so that it appears in our board

**Comment by kuisathaverat** [comment]
BDD is not used any more Teams will decide what they want to use and the output of the tests.
