### ISSUE TITLE
Re-enable "Deploying the "<os>" agent" scenario

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1658]
Since we have confirmed with @adam-stokes that the random failure for windows and fleet-server is not on the e2e-testing side, we'd like to skip the scenario, as it is adding noise to the builds. This issue will remind us to reenable the step once the project to run everything on VMs is completed.

**Comment by cachedout** [comment]
@mdelapenya Now that https://github.com/elastic/e2e-testing/pull/1659 has been merged, it seems as if this should be closed. Please do so if that's correct. :) Thanks!

**Comment by cachedout** [comment]
@mdelapenya Polite bump on the [question above](https://github.com/elastic/e2e-testing/issues/1658#issuecomment-957460560). :)

**Comment by mdelapenya** [comment]
First I'm going to rename the issue to "Re-enable..." 

I'd say that once @adam-stokes' work on the VM support is done and stable, we can re-enable this scenario

**Comment by cachedout** [comment]
@mdelapenya Could we please get an update on this one? Is this still in-progress or is something blocking it?

**Comment by mdelapenya** [comment]
First, I did not rename the issue 🤦 

Second, I'm not sure if we are running the tests on Windows again. @adam-stokes can you confirm this? I do not see the Windows machines in the parallel execution.

Once this is clarified, we can immediately enable the test back, and close this issue

**Comment by adam-stokes** [comment]
We need to write the ansible config for windows, I have initial code for it just need to finish it. Will do that this week

**Comment by cachedout** [comment]
> Will do that this week

@adam-stokes Was this done?

**Comment by mdelapenya** [comment]
I think we can close this one, as Windows support is done, running the `fleet_mode` scenarios
