### ISSUE TITLE
kind cluster logs are not available in Jenkins UI

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1725]
In #1690 we exported kind cluster logs and added to the existing `archiveArtifacts` step in Jenkins.

But they are actually not shown/archived in the UI.

Could it be possible that because we are passing a comma-separated list of artifacts, they are not properly resolved? I've checked that the files are exported:

>[2021-10-26T08:31:53.292Z] time="2021-10-26T08:31:53Z" level=info msg="Kind cluster logs exported" cluster=kind-ba56bf70-2a1f-4356-8909-5707b1a20805 path=/var/lib/jenkins/workspace/master-1859-b43b91c0-0547-4849-9fda-1bd17da57765/src/github.com/elastic/e2e-testing/outputs/kubernetes-autodiscover/kind-ba56bf70-2a1f-4356-8909-5707b1a20805

**Comment by cachedout** [comment]
@mdelapenya We've had this in the "in-progress" column for a week. Is there movement here or would you prefer that we move this into the backlog, or perhaps schedule it for an upcoming iteration?

**Comment by mdelapenya** [comment]
I'm going to investigate it this week, as past week I was oncall, where I discover it. Maybe I moved to the in-progress column too fast, but will work on that this week.
