### ISSUE TITLE
Do not use hardcoded UUIDs in JSON test files

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1905]
It could be the case where the tests, while running in parallel, could find some collisions.

In order to mitigate that, we could use a template and inject an UUID in those JSON files, used by fleet test suite. The files are:

- default_system_metrics.json
- linux_metrics.json
- metrics.json 

cc/ @IgorGuz2000 @adam-stokes

**Comment by adam-stokes** [comment]
Yea we definitely need to templatize these json files so that we can keep the UUID truly random
