### ISSUE TITLE
Use elastic package provider in all test suites

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1985]
@adam-stokes we are only using the elastic package provider in one test suite, right? Should we apply it everywhere?

_Originally posted by @mdelapenya in https://github.com/elastic/e2e-testing/issues/1959#issuecomment-1004994387_

**Comment by adam-stokes** [comment]
Yea this may also make things easier for deployments while investigating spread

**Comment by kuisathaverat** [comment]
obsolete
