### ISSUE TITLE
Kibana should not be built on ARM

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#2086]
As part of the move to run the elastic-agent in real VMs, we moved the stack provisioning to a dedicated stack runner

For the kibana+e2e integration success, we'd need:

- [ ] Remove the ARM builds for the build-my-kibana-pr job
- [ ] Make sure we pass the new kibana version (from the PR) to the stack provisioning code

cc/ @elastic/observablt-robots @adam-stokes

**Comment by cachedout** [comment]
@mdelapenya We don't seem to have a priority assigned to this and we don't seem to have it in the project board. Is there a specific reason that this was left out of recent triages or was it just an oversight?

cc: @kseniia-kolpakova
