### ISSUE TITLE
[Fleet] Parametrize and functionalize the check for the number of beats processes (currently only validates that 1 is running but 2 are the default)

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#218]
By default, there are two instances for the metricbeat process, one for monitoring the processes

cc/ @EricDavisX

**Comment by mdelapenya** [comment]
We are using `pgrep -n -l $process`. Removing the `-n` flag will list as many running process as they exist.

We should enable a manner to indicate the number of desired processes per process

**Comment by mdelapenya** [comment]
`preg -c $process` will give us the number of processes

**Comment by EricDavisX** [comment]
we should update the correct number of Filebeat processes too.

**Comment by ph** [comment]
@mdelapenya @EricDavisX Can you clarify what need to be done in that issue.?

**Comment by EricDavisX** [comment]
Yes, I can elaborate PH.  
We could / should turn this section where the pgrep -n is,
https://github.com/elastic/e2e-testing/blob/e41e1423e4ef2d31d71a8fb43aca70bd6ae4b0c6/e2e/utils.go#L359
and turn it into a function we can call with parameters for the number of the type of Beat we expect to see in order for it to return successful. 

Currently, we are running 2 filebeat and 2 metricbeat processes per the default settings and we do NOT yet validate that the correct number and type are running (or not).  And then we can use that function everywhere we assert against the number and type of running Beats.  This relates to start / stop tests, reboot, and stand-alone as well as Fleet monitored tests.  

It is maybe an easier task, a good one for someone to start with?
