### ISSUE TITLE
Test the Elastic Agent on Oracle Linux 8 operating system

### ISSUE THREAD

**Issue by jlind23** [elastic/e2e-testing#2196]
Add Oracle Linux 8 as a new Operating system.

**Comment by mdelapenya** [comment]
To start prioritising this, we would need to identify:

- what scenarios should use the Oracle Linux 8 OS
- when should they be ran: nightly builds, on PRs etc?
- in what maintenance branches?

**Comment by jlind23** [comment]
@mdelapenya it should be run on a nighlty basis on main branch.
Oracle Linux 8 should use the "Fleet" and the "running on beats" scenarios.
