### ISSUE TITLE
Consolidate Cucumber JSON reports into one single HTML file

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#2262]
The Jenkins pipeline is SCP'ing all JSON files at the end of the pipeline: https://github.com/elastic/e2e-testing/blob/fb6385e1732e3f1399da00d40e0504c4bfe74159/.ci/Jenkinsfile#L576-L579

It would be great if we can consolidate them all into one single JSON file, and the generate only one HTML file instead of as many as parallel stages we have.

The JSON file structure is defined as an array of objects (see https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/main/598/artifact/outputs/18.219.74.103/TEST-aarch64-fleet-dc95cdb6-2022-03-22-09%3A32%3A34.json/*view*)

```json
[
    {
        "uri": "features/running_on_top_of_beats.feature",
        "id": "running-on-top-of-beats",
        "keyword": "Feature",
        "name": "Running on top of Beats",
        "description": "  Scenarios for the Elastic Agent verifying the elastic-agent process runs alongside an existing Beats process.",
        "line": 2,
        "tags": [
            {
                "name": "@running_on_beats",
                "line": 1
            }
        ],
        "elements": [
            {
                "id": "running-on-top-of-beats;deploying-the-elastic-agent-with-enroll-and-then-run-on-top-of-filebeat;beats;2",
                "keyword": "Scenario Outline",
                "name": "Deploying the Elastic-Agent with enroll and then run on top of filebeat",
                "description": "",
                "line": 15,
                "type": "scenario",
                "tags": [
                    {
                        "name": "@running_on_beats",
                        "line": 1
...
```

So I guess it's possible to merge them all in one single JSON file at the end of the pipeline, and pass it to the HTML generator code, which receives the location of the cucumber reports here: https://github.com/elastic/e2e-testing/blob/fb6385e1732e3f1399da00d40e0504c4bfe74159/.ci/Jenkinsfile#L588-L597

**Comment by mdelapenya** [comment]
Another good improvement (thanks @kuisathaverat) would be to consolidate the external CSS into the file, so that [Jenkins CSP](https://www.jenkins.io/doc/book/security/configuring-content-security-policy/) does not complain about loading external resources

**Comment by mdelapenya** [comment]
There is a JS tool that could help with the CSS inlining: https://www.npmjs.com/package/css-inline-tool

**Comment by mdelapenya** [comment]
The QA Source team needs this to simplify how they report the test scenarios

**Comment by kuisathaverat** [comment]
We removed this test generation AFAIK are not used
