### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#2339]
This is the main tracking issue for including support for macos within e2e-testing. The idea is to use ogc provisioning tool with orka api support built in to accomplish this requirement.

ref: https://github.com/elastic/e2e-testing/issues/1682

**Comment by cachedout** [comment]
@mdelapenya Could you provide an estimate on how much time and effort this might take?

**Comment by mdelapenya** [comment]
I think we could get a lot of benefits of adopting OGC asap, as we would be removing most/all of the Ansible code to provision machines.

For the estimation, I'd like to sit with @adam-stokes before giving a random number

**Comment by cachedout** [comment]
@adam-stokes and @mdelapenya Let's hold off on doing an estimation until we know whether or not https://github.com/elastic/e2e-testing/pull/2626 will be viable.

**Comment by v1v** [comment]
> Can you please confirm and close if so?

https://github.com/elastic/e2e-testing/pull/2684 uses orka workers as host but the idea of this issue was to use ogc provisioning tool with orka api support to provision ephemeral workers outside of the CI

**Comment by cachedout** [comment]
@v1v Thanks for the follow-up. Just to clarify, do you mean that Mac OS workers are provisioned successfully as-needed inside the CI but that there is a need to _also_ be able to provision those workers when running the E2E test-suite in an ad-hoc manner on a local developer machine?

**Comment by v1v** [comment]
> do you mean that Mac OS workers are provisioned successfully as-needed inside the CI 

That's right

> that there is a need to also be able to provision those workers when running the E2E test-suite in an ad-hoc manner on a local developer machine?

That's what I thought it will be done as part of this issue. Additionally, what you just described is one of the use cases, IIUC, the vision about the e2e-testing was to decouple the provisioner from the tests. So far we have got ansible in some cases, in another cases, we use the local machine. If `ogc` could provide that level of abstraction, then the support for Orka could also be supported if needed.

**Comment by cachedout** [comment]
@v1v OK, thanks. I think that gives me what I need to know. Much appreciated.

**Comment by cmacknz** [comment]
Is there any chance we could prioritize adding support for Mac to the E2E tests? 

There was recently a significant change to the agent upgrade process on Mac, and ideally all we need to add test coverage for it is allow the existing E2E upgrade tests to run on Mac.

**Comment by cachedout** [comment]
@cmacknz Let me look into it. Does it need to be the Ventura OS?

**Comment by v1v** [comment]
> Is there any chance we could prioritize adding support for Mac to the E2E tests?

That's already done, see https://github.com/elastic/e2e-testing/issues/2339#issuecomment-1189098217

This [pipeline](https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-macos-daily-mbp/) is the one running the e2e-testing,  and build results are reported in Slack `ingest-notifications`

**Comment by cmacknz** [comment]
It does not need to be Ventura. 

@v1v I don't see Macs listed in the E2E platforms list: https://github.com/elastic/e2e-testing/blob/main/.ci/.e2e-platforms.yaml. How would we have an existing E2E test target a Mac OS worker? Am I just missing something here?

**Comment by v1v** [comment]
> @v1v I don't see Macs listed in the E2E platforms list: https://github.com/elastic/e2e-testing/blob/main/.ci/.e2e-platforms.yaml. How would we have an existing E2E test target a Mac OS worker? Am I just missing something here?

https://github.com/elastic/e2e-testing/pull/2626 uses orka workers as hosts. It does not use the `.e2e-platforms.yaml` at all, the `e2e-testing` allows to provision VMs or use the current machine as host, if the latter, then `provider= remote ` is the way to skip the provisioner IIRC

In other words, the pipeline in Jenkins requests Orka workers (ephemeral MacOS) and then deploy a Elastic stack in Elastic Cloud and run the tests in those Orka workers agains the Elastic Cloud.


The initial implementation to provision MacOS in AWS was closed in favour of using Orka, see https://github.com/elastic/e2e-testing/pull/2336#issuecomment-1150048989

**Comment by cmacknz** [comment]
Got it, thanks!
