### ISSUE TITLE
Add test support in Ingest Manager suite for Red Hat UBI Agent Docker container

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#239]
see comments here: https://github.com/elastic/integrations-dev/issues/188
 - we can likely copy + paste the current Agent stand-alone test and re-run it with this container instead in the config.

**Comment by mdelapenya** [comment]
We will need access to RedHat registry for the CI (and developers) (https://access.redhat.com/RegistryAuthentication)

**Comment by mdelapenya** [comment]
I added support to Redhat UBI 7 locally, and I can confirm that the agent is not restarted after the host is restarted.

**Comment by EricDavisX** [comment]
@mdelapenya we should double back with the team, I think they're referring to an Elastic internally created UBI - not one coming from Red Hat.  If I'm mis-undertsood I will enjoy be corrected soon. :)

So, Agent did start up initially at least?  That's a good first step.  

Regardless, the bug may be the same tho, after we get the image developed.  The persistence setup failing isn't totally surprising... I know little of Red Hat versions and how their components support would differ from other distros, perhaps @michalpristas would know briefly and can scope any fix with PH for when to prioritize?  If we dont know off the top, we can just log it when the time is right.  

Thanks for looking into this so quickly.  Depending on the answer to above, we'd potentially want to modify the scripting (or just add to it, and we can test / support both variants)

**Comment by mdelapenya** [comment]
We merged this feature: ubi8 images are there, running same scenarios than the stand-alone mode. For the RedHat ones, we'd need more work (authentication?)

Closing
