### ISSUE TITLE
Do not use aliases when checking versions

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#2500]
The e2e started originally with an implementation based on version aliases, ex. 8.2-SNAPSHOT. But after moving to hashed snapshots (a long time ago) we did not update the checks for aliases.

It seems that, in the middle of a bump to a patch version (from 8.2.0-SNAPSHOT to 8.2.1-SNAPSHOT) we have detected an chicken-egg issue regarding the artifacts API is not finding the 8.2.1 artifacts, because Beats CI was not able to produce the artifacts because the e2e failed 😱 

@v1v is triggering a 8.2 build using the 8.2-SNAPSHOT alias for BEAT_VERSION (https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/148/pipeline) which should pass as expected.

We are marking as top priority the elimination of any check for aliases in the e2e given we will always use hashed snapshots or released versions.

**Comment by v1v** [comment]
PR:
- https://github.com/elastic/e2e-testing/pull/2501
