### ISSUE TITLE
[OS Windows 10] : e2e setup-env command fails with error 49 on windows 10

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/e2e-testing#2511]
While running the ` make -C .ci setup-env`  command on Windows 10 powershell terminal, encountered below error:

```
PS C:\e2e_framework\e2e-testing> make -C .ci setup-env
make: Entering directory 'C:/e2e_framework/e2e-testing/.ci'
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe .runID
make[1]: Entering directory 'C:/e2e_framework/e2e-testing/.ci'
make[1]: '.runID' is up to date.
make[1]: Leaving directory 'C:/e2e_framework/e2e-testing/.ci'
python3 -m venv "C:/e2e_framework/e2e-testing/.venv"
make: *** [Makefile:55: setup-env] Error 49
make: Leaving directory 'C:/e2e_framework/e2e-testing/.ci'
```

**Comment by kuisathaverat** [comment]
It was failing at `$(VENV_DIR)/bin/pip3 install ansible requests boto3 boto` the virtual environment was not used at https://github.com/elastic/e2e-testing/blob/878a99d3f292613e705b9709b81cf842b2cb8e3e/.ci/Makefile#L52-L56, this should be fixed at https://github.com/elastic/e2e-testing/pull/3285
