### ISSUE TITLE
[Ingest Manager] Wrong package versions, need to update to using a :distribution image (tested w 7.10.0)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#253]
I ran the test recently with a 7.10 variable citation as below:

export DEVELOPER_MODE=true && ELASTIC_AGENT_VERSION=7.10.0-SNAPSHOT STACK_VERSION=7.10.0-SNAPSHOT godog -t @enroll

This pulled what seems to be the 7.8.x list of packages, just the original 9 of them that we had then.

I need help reviewing how the branches in e2e-testing are set up and what we might be able to do here... at a minimum, we could make sure the Registry image we use is always refreshed with latest Integration packages from the storage repo it points to (snapshot, staging, or production).

Its a bit of research to figure out, I don't know yet whats up.  Maybe Ruflin can help or SKH who has worked with getting the registry docker container in use in Kibana side.

screenshots:

Endpoint on at 0.8.0 which is old
<img width="373" alt="Screen Shot 2020-08-28 at 10 26 45 AM" src="https://user-images.githubusercontent.com/12970373/91579504-b9454400-e919-11ea-90db-8e4a485ef6a9.png">

base 9 integrations shown:
<img width="1255" alt="Screen Shot 2020-08-28 at 10 26 29 AM" src="https://user-images.githubusercontent.com/12970373/91579554-ccf0aa80-e919-11ea-8526-c5f82e4719c4.png">

**Comment by EricDavisX** [comment]
Maybe @ruflin can help or @skh who has worked with getting the registry docker container in use in Kibana side.  I know in non-docker'ed usage its set in kibana as a run-time variable, and is hardcoded in our real releases to the epr.elastic.co or the 7.8.x / 7.9.x specific versions.

In this usage, we're pulling a specific docker image, which is 8 weeks old: 
docker.elastic.co/package-registry/package-registry   41c150c8020efc53ab16e3bba774c62a419b51ea   cf997d5b163d
whats the specific thing we need to fix here, just pull the latest registry image routinely?  is there one of those?  ;)

<img width="1361" alt="Screen Shot 2020-08-28 at 10 42 11 AM" src="https://user-images.githubusercontent.com/12970373/91580580-52c12580-e91b-11ea-9c4c-dfa8ba5e10ef.png">

**Comment by ruflin** [comment]
It looks like this is a pretty old version where the `distributions` did not exist yet. I recommend you to switch to the distributions and either use a commit id or even better, a tagged version. Here `docker.elastic.co/package-registry/distribution:7.9.0` should work for you.

**Comment by EricDavisX** [comment]
@mdelapenya let us know if you need more

**Comment by mdelapenya** [comment]
I guess we discussed about that version in the past. Let's update the image tag for the registry

**Comment by mdelapenya** [comment]
> It looks like this is a pretty old version where the `distributions` did not exist yet. I recommend you to switch to the distributions and either use a commit id or even better, a tagged version. Here `docker.elastic.co/package-registry/distribution:7.9.0` should work for you.

It seems that ta is not present in the registry. What I do see is https://container-library.elastic.co/r/package-registry/distribution:production-7.9

**Comment by EricDavisX** [comment]
thanks @mdelapenya and @ruflin ... we still need to fix master/8.0 (and any 7.10 line we create), its somehow using older packages as well.  

the line we had that Manu's pr changed:
    image: docker.elastic.co/package-registry/distribution:staging
is what I would think is correct, so i need some help to confirm whats going on, on the package side.

**Comment by mdelapenya** [comment]
We could use the "snapshot" concept for the registry to use it in the master branch of this project, and detect regressions. For maintenance branches, let's use released ones. wdyt?

**Comment by EricDavisX** [comment]
That seems great.  I may be mis-understanding something.  My concern was that the code we had in place should have been working to pick up newer packages, but it wasn't (isn't, on master).

**Comment by ruflin** [comment]
@mdelapenya What you propose SGTM. This is also mostly in line with what Kibana uses as "default". On master it uses snapshot, on the other branches it uses production. If we have staging on e2e this is great, as we will detect issue in staging which is the goal!

@EricDavisX Not sure what code you refer to, but what was in the registry before the changes was from before we made changes on how packages are deployed with the 3 environments.

**Comment by mdelapenya** [comment]
PR is coming!

**Comment by EricDavisX** [comment]
Lets track the PR and discuss the architecture confusion I had off line later if needed.  Thanks guys
