### ISSUE TITLE
Kubernetes-based suites are failing

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#2558]
Build URL:  https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.17/691/pipeline

Happening when running Helm and k8s-autodiscover suites.

### Error
>dial tcp [::1]:10248: connect: connection refused.\n\n\tUnfortunately, an error has occurred:\n\t\ttimed out waiting for the condition\n\n\tThis error is likely caused by:\n\t\t- The kubelet is not running\n\t\t- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)\n\n\tIf you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:\n\t\t- 'systemctl status kubelet'\n\t\t- 'journalctl -xeu kubelet'\n\n\tAdditionally, a control plane component may have crashed or exited when started by the container runtime.\n\tTo troubleshoot, list all containers using your preferred container runtimes CLI.\n\n\tHere is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:\n\t\t- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'\n\t\tOnce you have found the failing container, you can inspect its logs with:\n\t\t- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'\n\ncouldn't initialize a Kubernetes cluster\nk8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:114\nk8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234\nk8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422\nk8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207\nk8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:147\nk8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826\nk8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914\nk8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864\nk8s.io/kubernetes/cmd/kubeadm/app.Run\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50\nmain.main\n\t_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nerror execution phase wait-control-plane\nk8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235\nk8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422\nk8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207\nk8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:147\nk8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826\nk8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914\nk8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864\nk8s.io/kubernetes/cmd/kubeadm/app.Run\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50\nmain.main\n\t_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by mdelapenya** [comment]
The most significative error that I see is 

```
The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
```

I've been googling a bit and it seems related to:
- https://www.makeuseoflinux.com/the-kubelet-is-unhealthy-due-to-a-misconfiguration-of-the-node-in-some-way-required-cgroups-disabled/
- https://discuss.kubernetes.io/t/kubeadm-init-error/7718
- https://stackoverflow.com/a/63721940

**Comment by ChrsMark** [comment]
cc: @elastic/obs-cloudnative-monitoring @gizas

**Comment by ChrsMark** [comment]
I see that the kind cluster cannot get initialised properly too:
```
[2022-05-24T05:51:11.399Z] ERRO[2022-05-24T05:51:03Z] Error executing command                       args="[create cluster --name helm-charts-test-suite --image kindest/node:v1.18.2]" baseDir=. command=kind env="map[]" error="exit status 1" stderr="Creating cluster \"helm-charts-test-suite\" ...\n • Ensuring node image (kindest/node:v1.18.2) 🖼  ...\n ✓ Ensuring node image (kindest/node:v1.18.2) 🖼\n • Preparing nodes 📦   ...\n ✓ Preparing nodes 📦 \n • Writing configuration 📜  ...\n ✓ Writing configuration 📜\n • Starting control-plane 🕹️  ...\n ✗ Starting control-plane 🕹️\nERROR: failed to create cluster: failed to init node with kubeadm: command \"docker exec --privileged helm-charts-test-suite-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6\" failed with error: exit status 1\n\nCommand Output: I0524 05:49:05.005117     167 initconfiguration.go:200] loading configuration from \"/kind/kubeadm.conf\"\n[config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta2, Kind=JoinConfiguration\nW0524 05:49:05.008646     167 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]\n[init] Using Kubernetes version: v1.18.2\nI0524 05:49:05.008823     167 kubelet.go:64] Stopping the kubelet\n[kubelet-start] Writing kubelet environment file with flags to file \"/var/lib/kubelet/kubeadm-flags.env\"\n[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"\n[kubelet-start] Starting the kubelet\n[certs] Using certificateDir folder \"/etc/kubernetes/pki\"\nI0524 05:49:05.109107     167 certs.go:103]
```

It seems to me that the main issue is `ERROR: failed to create cluster: failed to init node with kubeadm`.
Also I see that we use `v1.18.2` which has been out of support already. @mdelapenya shall we update the version to something newer like `v1.21`?

**Comment by mdelapenya** [comment]
> I see that the kind cluster cannot get initialised properly too:
> 
> ```
> [2022-05-24T05:51:11.399Z] ERRO[2022-05-24T05:51:03Z] Error executing command                       args="[create cluster --name helm-charts-test-suite --image kindest/node:v1.18.2]" baseDir=. command=kind env="map[]" error="exit status 1" stderr="Creating cluster \"helm-charts-test-suite\" ...\n • Ensuring node image (kindest/node:v1.18.2) 🖼  ...\n ✓ Ensuring node image (kindest/node:v1.18.2) 🖼\n • Preparing nodes 📦   ...\n ✓ Preparing nodes 📦 \n • Writing configuration 📜  ...\n ✓ Writing configuration 📜\n • Starting control-plane 🕹️  ...\n ✗ Starting control-plane 🕹️\nERROR: failed to create cluster: failed to init node with kubeadm: command \"docker exec --privileged helm-charts-test-suite-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6\" failed with error: exit status 1\n\nCommand Output: I0524 05:49:05.005117     167 initconfiguration.go:200] loading configuration from \"/kind/kubeadm.conf\"\n[config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta2, Kind=JoinConfiguration\nW0524 05:49:05.008646     167 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]\n[init] Using Kubernetes version: v1.18.2\nI0524 05:49:05.008823     167 kubelet.go:64] Stopping the kubelet\n[kubelet-start] Writing kubelet environment file with flags to file \"/var/lib/kubelet/kubeadm-flags.env\"\n[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"\n[kubelet-start] Starting the kubelet\n[certs] Using certificateDir folder \"/etc/kubernetes/pki\"\nI0524 05:49:05.109107     167 certs.go:103]
> ```
> 
> It seems to me that the main issue is `ERROR: failed to create cluster: failed to init node with kubeadm`. Also I see that we use `v1.18.2` which has been out of support already. @mdelapenya shall we update the version to something newer like `v1.21`?

+1 to bumping the versions of k8s, and possibly helm. Would you mind adding the versions you expect are the correct ones? 🙏

**Comment by ChrsMark** [comment]
Based on https://github.com/elastic/beats/blob/ea207346d651448b8917b0791b2b117b9f9b9212/deploy/kubernetes/Jenkinsfile.yml#L21 I would go for `v1.23.4`.

**Comment by mdelapenya** [comment]
> v1.23.4

Do you think we can automate the bump of that version alongside Beats? @v1v, do you foresee a version bump here too?

**Comment by mdelapenya** [comment]
Yes, I mean bumping the e2e whenever Beats receives an update. In my mind I imagine beats defining the right versions for kubernetes/helm/kind, and then we update the consumers (the e2e-testing project).

> the bump will always be PR based
Yes, that's the expected way to do it :)
