### ISSUE TITLE
Rename ingest-manager to Fleet everywhere

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#267]
update Fleet APIs used in 8.0 and 7.10+ (should not be back-ported to 7.9)

**Comment by EricDavisX** [comment]
this is quite low priority to me... but would be good to get done by 7.11-ish or 7.12 even.  Do be mindful not to backport it to releases where the change hasn't taken place, to avoid any more confusion on naming, lol.

**Comment by EricDavisX** [comment]
also - there is an issue in Kibana or integrations-dev repo perhaps, but only user facing strings and api calls will change, the Kibana plugin itself is unlikely to change (so references to Ingest Manager will still be all over Elastic code...)

**Comment by mdelapenya** [comment]
Relates https://github.com/elastic/e2e-testing/issues/342

**Comment by EricDavisX** [comment]
I agree it makes more sense to do it now that the team has decided to do further rename work in Fleet apis for 7.10 - we may as well rename stuff where it makes sense

**Comment by mdelapenya** [comment]
I think we can close this one, as #342 was merged
