### ISSUE TITLE
Support on downloading Agent logs from Node VM

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/e2e-testing#2821]
Currently, when we are running tests through CI, we see there is no way to see agent logs if agent is not installed properly, untill we ssh-node to check errors. So, could it be possible to download them from node and check out for error logs recorded on agent installed.

This will help us validate Agent behaviour and catch potential errors more early durning running of tests on builds.

cc @mdelapenya

**Comment by kuisathaverat** [comment]
It was added at https://github.com/elastic/e2e-testing/pull/3285, now the logs are uploaded to artifacts in the CI. In `artifacts/output/Test_Suit_Name` you have Docker, Kubernetes, and Elastic Agent logs for the test Suit
