### ISSUE TITLE
Support for testing Build candidates during manual test runs

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/e2e-testing#2834]
As of now, we are currently running tests on snapshots builds through CI jobs, however if we wish to validate the BC builds  manually, we get errors while fetching artifacts during runs.

So to handle this, we need to add staging artifact links under our scripts so that BC builds can be validated through local runs.

BC builds artifact for reference will be like: https://staging.elastic.co/8.3.3-a7e777e7/summary-8.3.3.html

cc @mdelapenya

**Comment by mdelapenya** [comment]
We need to grant access from the remote instances to `docker.elastic.co/observability-ci`, as the BC Docker images needed to bootstrap the stack are there.

**Comment by kuisathaverat** [comment]
obsolete
