### ISSUE TITLE
Installation binaries are not properly cleaned up between scenarios

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#2861]
I'm seeing this error from time to time, causing the tests to fail when found.

The error message is:

> [2022-07-27T14:29:43.212Z] time="2022-07-27T14:29:43Z" level=error msg="Error executing command" args="[/root/.op/elastic-agent/elastic-agent-8.4.0-SNAPSHOT-linux-x86_64 /root/.op/elastic-agent/elastic-agent]" baseDir=. command=mv env="map[]" error="exit status 1" stderr="mv: cannot move '/root/.op/elastic-agent/elastic-agent-8.4.0-SNAPSHOT-linux-x86_64' to '/root/.op/elastic-agent/elastic-agent/elastic-agent-8.4.0-SNAPSHOT-linux-x86_64': File exists\n"

**Comment by kuisathaverat** [comment]
resolved at https://github.com/elastic/e2e-testing/pull/3285
