### ISSUE TITLE
Confirmation on Standalone agent reference being used in E2E scripts

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/e2e-testing#2930]
While evaluating the standalone agent scripts under the E2E Fleet suite, we have observed that a standalone agent is deployed on a docker Container and visible under Fleet tab.

As per our understanding through [guide ](https://www.elastic.co/guide/en/fleet/master/elastic-agent-configuration.html) Standalone are not managed by Fleet. So, when we deploy standalone agents, they dont show up in Fleet and only stream data on data stream tabs and logs & metrics entries are available under Discover tab.

However, when we are running standalone agent through scripts they are shown up in Fleet tab too.

**Screenshots for references:**
![standalone agent](https://user-images.githubusercontent.com/72375798/183921273-144e9007-0710-457e-8725-0cd1fc57c335.jpg)

![Standalone_agent details](https://user-images.githubusercontent.com/72375798/183921306-afef4b57-5a8b-46eb-a322-c7f9fcf39e9e.jpg)
![Standalone_agent_datastreams](https://user-images.githubusercontent.com/72375798/183921326-55c03ad0-4cd1-4e40-a7c1-cc92b482e75e.jpg)

So, Could anybody help us to understand that how standalone agents behaviour is assumed in current automated feature scripts.

**Comment by kuisathaverat** [comment]
The standalone deployment is configured to enroll, so it appears in fleet

https://github.com/elastic/e2e-testing/blob/main/e2e/_suites/fleet/stand-alone.go#L150-L152

**Comment by dikshachauhan-qasource** [comment]
Hi @kuisathaverat 

Thanks for the feedback on ticket. 

I will add this ticket to next agenda call, as I have bit open queries on same.

cc @cachedout 

Thanks
