### ISSUE TITLE
[Platform Support]: [Elastic Agent] Support for CentOS Stream 8

### ISSUE THREAD

**Issue by jlind23** [elastic/e2e-testing#3128]
### Platform ID

CentOS stream 8

### Description

CentOS stream 8

### AWS AMI identifier

?

### Instance Type

?

### Root user

centos

### What scenarios should be run using this platform?

```Markdown
Fleet scenarios
```

**Comment by cachedout** [comment]
@pazone I've added this to the DX board
@kuisathaverat We'll need to find room for this in an upcoming iteration and then give @jlind23 an ETA.

**Comment by cachedout** [comment]
@kuisathaverat I added this to iteration 13. Please let me know if that's a problem.

**Comment by kuisathaverat** [comment]
> I added this to iteration 13. Please let me know if that's a problem.

@cachedout I do not think so, in case we see we cannot do it, we can drop other issue and make this one.

cc @pazone

**Comment by kuisathaverat** [comment]
@pazone check if it is duplicated with https://github.com/elastic/observability-robots/issues/1438

**Comment by nick-alayil** [comment]
Is it correct that we've completed all tasks required for claiming elastic-agent support for Cent OS Stream 8 in 8.6? In light of https://github.com/elastic/observability-robots/issues/1438 being closed, I just wanted to ask.

**Comment by pazone** [comment]
Sure. We can already use it. https://github.com/elastic/e2e-testing/blob/main/.ci/.e2e-platforms.yaml#L9
And in a couple of days it will even work faster
