### ISSUE TITLE
Destroy make commands are unable to delete provisioned aws VMs

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/e2e-testing#3304]
While using `make .C -ci destory-stack` or `make -C .ci destroy-node` commands, we expected the provisioned aws VMs are deleted. However, these VMs are not destroyed. If we filter out the VMs through run IDs on AWS console under US East (Ohio) region, VMs still be available there in `running` state.

So , we need to track the working of these commands so that actual expected workflow from it can be achieved.

**Comment by dikshachauhan-qasource** [comment]
cc @cachedout @pazone

**Comment by kuisathaverat** [comment]
resolved at https://github.com/elastic/e2e-testing/pull/3285

**Comment by dikshachauhan-qasource** [comment]
Hi @kuisathaverat 

Thanks for fixing this out,

We are observing that, we are able to terminate the provisioned AWS instances using the `destroy-node` and `destroy-stack `commands.

Thanks!!
