### ISSUE TITLE
Design Doc: New E2E testing infrastructure provisioning

### ISSUE THREAD

**Issue by pazone** [elastic/e2e-testing#3394]
We need to clearly separate infrastructure provisioning and tests execution. 
Try different approaches like Elastic Terraform provider, testcontainers and oblt_cli.

**Comment by cachedout** [comment]
@pazone I am trying to understand the status of this issue. It appears that you opened the issue but then immediately set the `Status` field to `Done` but you left the issue open. What is the _actual_ status of this task?
