### ISSUE TITLE
[Fleet] duplicate file for legacy backwards compatibility support apis due to ingest_magement -> fleet api change

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#349]
further work from:
https://github.com/elastic/e2e-testing/issues/342

This is just a place-holder.  The urgent 'api updates' work is in pr already, here:
https://github.com/elastic/e2e-testing/issues/267

...for this ticket, we should duplicate the apis that remain as support for backwards compatibility of 7.9 Agents calling in to 7.10 or beyond Fleet (eventually this bcw support can be removed)

based on info here:
https://github.com/elastic/kibana/pull/79193

**Comment by mdelapenya** [comment]
Hey @EricDavisX, we renamed the APIs in #348, affecting master branch, but not backported to 7.9.x.

Is this issue still valid?

**Comment by EricDavisX** [comment]
yes.  this is team feature testing work that could be (needs to be) done to validate that the 'old' apis still work.  we'll need to copy / paste some implementation code and do new feature file work to validate that 7.10 and beyond still support the older api calls, until such time as we remove them as they are old enough that no agent should reasonably be using it in the noted version.

**Comment by EricDavisX** [comment]
we've moved so far past the old APIs that I think it isn't worthwhile to work this now.  closing as not done and that is ok.
