### ISSUE TITLE
[Fleet, Agent & Endpoint] support raw yaml input for global config (for Elasticsearch)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#350]
This is feature work from:
https://github.com/elastic/kibana/issues/75913

more details there, but it would be great to set this up in e2e-testing to have it validated that it works with a real Agent, Endpoint and Kibana.

I expect the work for this to include, but is not limited to:

setting up a new feature file with a copy of the current Agent & Endpoint file, here https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/ingest-manager/features/agent_endpoint_integration.feature

updating the setting of the global ES Fleet value, to make it parameterized with an enum.
 - which is precluded by breaking it out of the implementation into a separate step to be exposed in feature file which we can then insert into each of the scenarios we want from above

ensuring we have a good test / sample yaml that is valid for our docker usage and putting it into the test framework

**Comment by kuisathaverat** [comment]
The proposal that uses `oblt-cli` allows to pass custom settings to all components of the stack.
