### ISSUE TITLE
k8s-autodiscovery-test (7.17) failed

### ISSUE THREAD

**Issue by v1v** [elastic/e2e-testing#3642]
```
--- Failed steps:

  Scenario: Logs collection from short-living cronjobs # features/elastic_agent_standalone.feature:22
    And "a short-living cronjob" is deployed # features/elastic_agent_standalone.feature:24
      Error: failed to deploy 'a short-living cronjob': exit status 1

  Scenario: Logs collection from short-living cronjobs # features/filebeat.feature:18
    And "a short-living cronjob" is deployed # features/filebeat.feature:20
      Error: failed to deploy 'a short-living cronjob': exit status 1
```

See https://github.com/elastic/e2e-testing/actions/runs/6138671269/job/16655778644#step:6:175

https://github.com/elastic/e2e-testing/actions/runs/6138671269/workflow#L37-L43 are the steps that run in the GitHub action.

@constanca-m , I've seen you enabled the support for Kind in https://github.com/elastic/e2e-testing/pull/3612 , do you happen to know who can look at the above test failures? 🙏

**Comment by v1v** [comment]
@tommyers-elastic , a few questions regarding the e2e-testing for the k8s-autodiscovery-test

* Build failures are notified by slack, but it's reported to `#observablt-bots`, see https://elastic.slack.com/archives/C01APBTSM0V/p1694629963916879. I don't know if the infraobs platform team see them, do you think those messages could be sent to a different channel for a higher visibility? 
* e2e-testing fails when targeting `7.17`, do you happen to know who is the team/person responsible for reviewing them? 

Thanks

**Comment by gizas** [comment]
@v1v opened above PR https://github.com/elastic/e2e-testing/pull/3646
I think the PR will run the failing test is not it?
