### ISSUE TITLE
Investigate why the endpoint policy is not getting to the RUNNING state

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#375]
The events obtained are in the DEGRADED state:

"Application: endpoint-security--7.9.2[ab9e7d89-a285-4cf2-be3b-65d9d87ee096]: State changed to DEGRADED: Protecting with policy {b89ee120-1045-11eb-a219-ff34b6e24c16}"

**Comment by EricDavisX** [comment]
this is not seen any more - all tests are passing for all branches recently, closing out.
