### ISSUE TITLE
[helm-chart] check all charts default resources

### ISSUE THREAD

**Issue by jmlrt** [elastic/e2e-testing#448]
Currently [aResourceContainsTheKey](https://github.com/jmlrt/e2e-testing/blob/3c485b43dee6098f20cd197151c0e53626b9fa4d/e2e/_suites/helm/helm_charts_test.go#L90) can test only one resource for a specific kind in each charts.

Some charts have more than multiple resources of the same kind, for example [Metricbeat]() chart deploy one ConfigMap for the [DaemonSet](https://github.com/elastic/helm-charts/blob/f0681c12b72bf033407718d09eb17efc3c210667/metricbeat/templates/configmap.yaml#L21-L37) and another for the [Deployment](https://github.com/elastic/helm-charts/blob/f0681c12b72bf033407718d09eb17efc3c210667/metricbeat/templates/configmap.yaml#L39-L53).

It could be great to be able to check every resources especially when there is more than one resource for a specific kind.

**Comment by kuisathaverat** [comment]
deprecated
