### ISSUE TITLE
[Fleet] Split off Metricbeat and Filebeat based Agent assessments into separate files (like we do for Endpoint)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#530]
This would provide:
 - better parallelization (which will matter if / when we have more tests)
 - easier assessment of Docs & communications in ES / Fleet Server & Kibana

I propose that with current support added to the framework building blocks, we can now easily set policy to be what we want and exclude what we don't want so we can assess the individual Beats.

Came up out of a discussion with PH.

**Comment by ph** [comment]
I think its a good idea, there are multiple case I see from for filebeat.

- The system integration where local logs are collected.
- The custom log integration where we can specify the file to collect.

The latter would allow us to have a more explicit assert.

**Comment by mdelapenya** [comment]
Working on this. This is a great idea @EricDavisX , as I see two potential benefits:

1. reduce the CI build, as all the wait-for-process logic will be executed in the new feature file (in a parallel CI branch)
1. decouple errors related to backend process from other type of errors

Thanks!
