### ISSUE TITLE
Setup branch for 7.11.x e2e-testing repo and retire prior branch from Jenkins nightly tests

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#543]
Every release we should:
retire the current GA product test line (7.10.x) as the new one goes out
branch the tests for the new coming GA (7.11.x)
 - this needs to be manually done in repo, with some variable / inputs in Jenkinsfiles updated
 - for Fleet we may want to update the 'stale' version Agent in test in master and 7.x line?
 - any other updates, like Helm Chart versions etc?  we should gather all info in one ticket so it is easier to repeat.  :)

All the while:
- .x branch continues on.  It becomes the initial tests for next GA (this means 7.12 now)
- master (8.0) continues on.  

Note, we missed shutting down 7.9 last time, but its ok - we can do it now, too.

**Comment by EricDavisX** [comment]
@mdelapenya you think we need to do anything else?  I will take a stab at this.

**Comment by mdelapenya** [comment]
wdyt about a Github issue template with checkboxes for this?

**Comment by EricDavisX** [comment]
I didn't get far enough to PR it before winter break, I did start looking at the code tho.  @mdelapenya are you available to hack this out?  If we leave a good trail in this issue and PR over what changes are required throughout the repo I can easily do it subsequent cycles.  For now I wasn't 100% confident, plus the tests are failing for master line so it wasn't a great time to do it without a steady hand.

**Comment by mdelapenya** [comment]
Let's talk about it tomorrow. I already started with it locally
