### ISSUE TITLE
[Ingest Manager] slack channel posts from nightly branch runs of e2e for Ingest Manager testing not showing up

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#546]
This started happening sometime Wednesday Dec 16 (2 days ago now).  The posts for Wednesday early AM EST are there, but Thursday / Friday relating runs are not showing.

I'm not even 100% the runs are scheduled and executing correctly (that would be a root cause if so). 

There was known Beats Jenkins maintenance on Wednesday (I believe) that may related.  I will look to investigate as possible (after I return from vacation).  

I don't see any relating PRs merged that would cause the change to the Beats CI execution.  Anyone thoughts?
https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/

Screenshot of Wednesday's posts:
<img width="582" alt="Screen Shot 2020-12-18 at 1 44 44 PM" src="https://user-images.githubusercontent.com/12970373/102649867-f424ef00-4137-11eb-9901-e9e18a92b93e.png">

**Comment by kuisathaverat** [comment]
The jobs are not scheduled due to the change of the Jenkins instance, I have re-ran the jobs to schedule them.
