### ISSUE TITLE
Merge CLI and e2e dirs into the root dir

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#557]
This will prevent for false positives when linting

**Comment by mdelapenya** [comment]
@jsoriano I'd like to know your opinion about how to address this, as you have more experience with larger Go codebases and layouts.

**Comment by jsoriano** [comment]
> This will prevent for false positives when linting

What kind of issues are you having with current layout?

**Comment by mdelapenya** [comment]
Linting in precommit causes many false positives, see https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/92/tests (Sanity checks section).

Also VSCode many times has hard times with IntelliSense for autocomplete and lint, not sure if it's because of the multi-module project.
