### ISSUE TITLE
Support running the E2E against the local artifacts generated by the Beats repository

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#653]
It would be a nice-to-have to run the E2E against the Beats locally generated artifacts, improving the developer experience.

To generate the artifacts:
```shell
export THE_BEAT="elastic-agent"
cd x-pack/$THE_BEAT; SNAPSHOT=true PLATFORMS=darwin   DEV=true mage package
```
for docker images set platform:
```shell
PLATFORMS="+all linux/amd64"
```

An initial idea could be passing an environment variable with the location of the local Beats repo, so that it's possible to get the artifacts from that path. Something like `BEATS_LOCAL_PATH=/tmp/foo`
 
@elastic/observablt-robots @michalpristas @EricDavisX @ph,  thoughts?

**Comment by mdelapenya** [comment]
In the conversation we mentioned the idea of adding a command in Beats' build system, so that it fetches current version of the E2E tests (per maintenance branch) and automatically triggers them.

**Comment by EricDavisX** [comment]
the support for windows is logged separately and being considered for near term (Q1) roll out.
