### ISSUE TITLE
Add a stage at PR level for running smoke tests for the different combinations of artifacts

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#701]
We'd like to verify that retrieving artifacts from all valid sources is working for the multiple combinations that exist. I can picture a stage that runs only for PRs where we run an integration test that fetches the artifacts for different use cases. 

We have unit tests demonstrating that the generation of the artifact name is correct for all use cases, but we'd like to confirm that the download process actually works, in the form of an integration test.

cc/ @elastic/observablt-robots thoughts?

Following tables describe all possible use cases and the artifacts used for each of them:

## Testing Beats PRs
When a PR is sent to Beats, and the packaging job is triggered, then the CI will run the E2E tests using the generated artifacts for that PR.
| Environment  | Artifact | Expected artifactory | Download Path | Notes |
|--------------|---------|---------------------|-----------------|-------|
| Beats CI | elastic-agent | GCP | $bucket/pull-requests/pr-ID | Needs</br> BEATS_USE_CI_SNAPSHOTS=true</br> ELASTIC_AGENT_VERSION=pr-ID |
| Beats CI | metricbeat | GCP | $bucket/pull-requests/pr-ID | Needs</br> BEATS_USE_CI_SNAPSHOTS=true</br> METRICBEAT_VERSION=pr-ID |

## Testing Beats Branches
When a merge commit happens at Beats, and the CI build passes, then the CI will run the packaging job for that merge commit in that branch, running the E2E tests using the generated artifacts for that branch.
| Environment  | Artifact | Expected artifactory | Download Path | Notes |
|--------------|---------|---------------------|-----------------|-------|
| Beats CI | elastic-agent | GCP | $bucket/snapshots | Needs BEATS_USE_CI_SNAPSHOTS=true |
| Beats CI | metricbeat | GCP | $bucket/snapshots | Needs BEATS_USE_CI_SNAPSHOTS=true |

## Testing Beats from local workspace
When working on Beats, it's possible to run the E2E tests using the generated artifacts for the current Beats workspace.
| Environment  | Artifact | Expected artifactory | Download Path | Notes |
|--------------|---------|---------------------|-----------------|-------|
| Beats CI | elastic-agent | Local Beats repository | $BEATS_LOCAL_PATH/x-pack/elastic-agent/build/distributions | Needs</br> Artifacts must be packaged at Beats repo</br> BEATS_LOCAL_PATH=/PATH/TO/BEATS_GIT_REPO |
| Beats CI | metricbeat | Local Beats repository | $BEATS_LOCAL_PATH/metricbeat/build/distributions | Needs</br> Artifacts must be packaged at Beats repo</br> BEATS_LOCAL_PATH=/PATH/TO/BEATS_GIT_REPO |

## Developing the E2E project
When working on the E2E, it's possible to run the E2E tests using the official artifacts for Beats.
| Environment  | Artifact | Origin | Expected artifactory | Download Path | Notes |
|--------------|---------|-------|---------------------|-----------------|-------|
| Beats CI | elastic-agent | Branch | Elastic's artifactory | https://artifacts-api.elastic.co/v1/search/$VERSION/elastic-agent |  |
| Beats CI | metricbeat | Branch | Elastic's artifactory | https://artifacts-api.elastic.co/v1/search/$VERSION/metricbeat | |
| Local/Beats CI | elastic-agent | PR | Elastic's artifactory | https://artifacts-api.elastic.co/v1/search/$VERSION/elastic-agent |  |
| Local/Beats CI | metricbeat | PR | Elastic's artifactory | https://artifacts-api.elastic.co/v1/search/$VERSION/metricbeat | |

## Bisecting an error in Beats
When tracing back an error on Beats, it's possible to run the E2E tests using the artifacts that were generated for a specific Beats commit.
| Environment  | Artifact | Expected artifactory | Download Path | Notes |
|--------------|---------|---------------------|-----------------|-------|
| Local | elastic-agent | GCP | $bucket/commits/SHA1/elastic-agent | Needs</br> BEATS_USE_CI_SNAPSHOTS=true</br> GITHUB_CHEK_SHA1=07b63dd4a2ece5642ea85a9beba00c3319062291 |
| Local | metricbeat | GCP | $bucket/commits/SHA1/metricbeat | Needs</br> BEATS_USE_CI_SNAPSHOTS=true</br> GITHUB_CHEK_SHA1=07b63dd4a2ece5642ea85a9beba00c3319062291 |

>This bisect process could be automated on CI, having a dedicated pipeline receiving initial commit, end commit, and the script to run tests.

**Comment by v1v** [comment]
I'd prefer to use the download path `$bucket/commits/SHA1/` for the `Testing Beats PRs/Branches` sections. Otherwise, there might be a chance the `$bucket/pull-requests/pr-ID` or `$bucket/snapshots` could be regenerated with a new packaging.

**Comment by mdelapenya** [comment]
Good point. I think we can update that to always use the commit SHA, and it will simplify the bucket path calculation.
