### ISSUE TITLE
Consume local helm charts for metribeat and filebeat

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#706]
Leverage the BEATS_LOCAL_PATH to get the helm charts that were built in the local workspace.

**Comment by mdelapenya** [comment]
As the helm charts are built in https://github.com/elastic/helm-charts, instead of the above, it would be great to trigger the helm charts tests on changes in the APM Server, filebeat or metricbeat charts. cc/ @jmlrt

**Comment by kuisathaverat** [comment]
deprecated
