### ISSUE TITLE
Bump observability helm charts

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#747]
We are consuming 7.10.0 version, but 7.10.2 is out

cc/ @jmlrt

**Comment by jmlrt** [comment]
We should release 7.11.1 in the end of the week or next week. It may be worth waiting for bumping.

**Comment by jmlrt** [comment]
Note that we also release 6.8.x versions of the charts (6.8.14 is expected today if there is no issues).

**Comment by mdelapenya** [comment]
Ah cool! We do have a 6.8 branch, so we could take benefit of it to run the helm chart tests there.

**Comment by mdelapenya** [comment]
About the 7.11.1, let's make it then
