### ISSUE TITLE
Create 7.12.x branch

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#802]
It must run the tests against Beats 7.12 branch

@EricDavisX @michalpristas should we deprecate 7.10.x after that?

**Comment by EricDavisX** [comment]
The most safe and best process I see would be to create the 7.12 branch as soon as FF is called and Infra starts building BC1.  If we do this in sync we can assure coverage over the new line.

I'm not 100% sure, does Elastic support current minor release minus -1 ?  If so, we should retire the next most oldest line only AFTER the newly created .0 (in this case 7.12) release is shipped.  If we are sure we won't ever release a 7.10.x patch then we can retire it now.

**Comment by mdelapenya** [comment]
Closing a 7.12.x is live, running nightly jobs for 7.12 release
