### ISSUE TITLE
[Integrations][Agent] Add tests for System Integration package for Windows Agent (all of the various metrics and logs that can be collected)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#822]
We have a 'depth of test' ticket logged here:
https://github.com/elastic/e2e-testing/issues/313

We aren't yet validating the data streamed into ES unless the above is coverd.

This ticket here is implemented to go deeper for Windows available datasets / fields

See lots of test nuance and details in: https://github.com/elastic/integrations/issues/276

Note, not all of the below are turned on by default, so a policy change in those cases is required as part of the scenario.  To be safer, we could put in a 'set this option if not set' step.  Asserting which are on or off by default itself could be a useful test, but maybe not very interesting or error prone (not sure).  

-------------
Logs:
 - [ ] TBD

Metrics (need to parse this list down for Windows specificity!)
- [ ] System core metrics
- [ ] System cpu metrics
- [ ] System diskio metrics
- [ ] System entropy metrics
- [ ] System filesystem metrics
- [ ] System fsstat metrics
- [ ] System load metrics
- [ ] System network metrics
- [ ] System network summary metrics
- [ ] System process_summary metrics
- [ ] System raid metrics
- [ ] System service metrics
- [ ] System socket metrics
- [ ] System socket_summary metrics
- [ ] System uptime metrics
- [ ] System users metrics

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have performed testing around system package v 11.0 on 8.0 snapshot build using all OSs and found it working fine.

Test run Link is as follows:  [Ingest Manager for System package v0.11.2 on 8.0snapshot](https://elastic.testrail.io/index.php?/runs/view/1435)

Build details:
BUILD 41248
COMMIT 716e2f78166346267bae9ae2190c2d35cad8ec01
Artifact link : https://artifacts-api.elastic.co/v1/search/8.0-SNAPSHOT

Please let us know if anything further is required.

Thanks
QAS

**Comment by EricDavisX** [comment]
excellent, i'll close this out then.
