### ISSUE TITLE
[Agent] Account for 'Agent install' Go side code paths for Windows artifacts (maybe just branch them?)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#823]
Windows hosts are not supported yet for e2e-testing scenarios, but we expect to have support sometime (maybe even soon?) 

- as part of that we expect to modify the CI side for Agent builds and modify some general infrastructure calls here in e2e-testing as well, but a low level item for the feature team is to do the work needed to branch / support the methods that call any host-biased command-line instruction (where it would be different for Windows vs Linux, like the install step)

**Comment by kseniia-kolpakova** [comment]
It will be done as part of https://github.com/elastic/observability-robots/issues/474
