### ISSUE TITLE
[Fleet] [Agent] For Managed Agent / Managed Policy - we need to add tests in to e2e for coverage not already in place on Kibana side (or Agent unit tests)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#857]
This is a place-holder ticket where we can add details.  Please link to the feature tickets I don't have it handy.  :S

@jfsiii if you want to work with me to lay out the obvious test cases, like validating the managed agents cannot be changed from policy and the policy cannot be changed, that is a start.  I don't know if you have those covered well on Kibana side or in Unit tests, but at least 1 'end to end' test is warranted either way.

The manual test team has been assigned a review over the feature and may have questions which can lead to more test cases.  We'll manage that separately and add back items here as appropriate.

If you want to focus first (or only) on the Fleet / Kibana side validation that is a-ok, keep in touch.
- [ ] validating a managed agent cannot be changed from its managed policy via Kibana user exposed API 
- [ ] validating a managed policy cannot be changed by user exposed Kibana API
- [ ] others?  the above was just a presumed easy start to the list

**Comment by jfsiii** [comment]
@EricDavisX happy to work with you on this. We already have unit tests and API tests for many of the actions.

Unit tests are in x-pack/plugins/fleet/**/*.test.ts. HTTP API tests are in x-pack/test/fleet_api_integration/apis/**/*.ts

Searching for "managed" in either should find them, like https://github.com/elastic/kibana/blob/b5522ed30c1445a9ad07c8f7d95771e1f6b95609/x-pack/plugins/fleet/server/services/agents/reassign.test.ts#L41 or https://github.com/elastic/kibana/blob/b5522ed30c1445a9ad07c8f7d95771e1f6b95609/x-pack/test/fleet_api_integration/apis/agents/reassign.ts#L92
