### ISSUE TITLE
Support testing over linux-arm64.tar.gz, aarch64.rpm and arm64.deb artifacts (Docker handled separately)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/e2e-testing#864]
Further towards https://github.com/elastic/observability-robots/issues/315
and 
https://github.com/elastic/beats/issues/22893
and
https://github.com/elastic/infra/issues/25762

we have not only the Docker image to validate, but 3 more arm64 linux artifacts to add to the mix.

**Comment by mdelapenya** [comment]
@EricDavisX #707 will handle this, as it will fetch ARM artifacts when tests are run, using ARM workers on CI.

**Comment by EricDavisX** [comment]
Excellent - I didn't realize we had e2e-testing repo CI ARM64 workers - I only saw the Docker work going on.  And I see Victor's efforts on ARM64 workers for Beats, but didn't realize it would be inherited 'for free' into e2e-testing usage as it is now... or, do we still have other work to do to make use of them once they are in place?

**Comment by mdelapenya** [comment]
Yep, this means the CI will provide ARM workers, and we will use them to spin up our very same Docker containers **BUT** in the ARM flavour: using the `platform` attribute in compose files and selecting the proper binary file when downloading them from the artifactories (Elastic's or GCP buckets)
