### ISSUE TITLE
Investigate failures for "uninstall-host" scenario

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#895]
The `@uninstall-host` scenario is failing consistently for Centos and Debian, ~~although not failing for Debian~~.

>UPDATE: after running the tests more times, I realised that both OSs are affected

```gherkin
@uninstall-host
Scenario Outline: Un-installing the installed <os> agent
  Given a "<os>" agent is deployed to Fleet with "tar" installer
  When the "elastic-agent" process is "uninstalled" on the host
  Then the file system Agent folder is empty
    And the agent is listed in Fleet as "offline"

@centos
Examples: Centos
| os     |
| centos |

@debian
Examples: Debian
| os     |
| debian |
```

I tried running it locally with different timeout factors: 3 and 5 (which means waiting 2 minutes * timeoutFactor until the existing before the condition is satisfied), and that scenario consistently fails.

## Steps to reproduce

1. Run this command
```shell
SUITE="fleet" TAGS="fleet_mode_agent && uninstall-host && centos" \
TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true \
make -C e2e functional-test
```

```shell
SUITE="fleet" TAGS="fleet_mode_agent && uninstall-host && debian" \
TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true \
make -C e2e functional-test
```

#### Expected behaviour
The scenario passes, so the agent is listed in Fleet as "offline"

#### Current behaviour
The scenario does not pass, because the agent is always in the "Updating" state, so the error thrown by the scenario is related to exhausting the max timeout, caused by the last step: `    And the agent is listed in Fleet as "offline"`.
<img width="1249" alt="Screenshot 2021-03-16 at 10 18 38" src="https://user-images.githubusercontent.com/951580/111285038-06340200-8641-11eb-892f-e82b951897c3.png">

cc/ @michalpristas @EricDavisX @ph

**Comment by michalpristas** [comment]
can you also share a failure message? is it last step which is failing?

**Comment by mdelapenya** [comment]
I was doing exactly that. Updated the description

**Comment by kseniia-kolpakova** [comment]
Issue in beats https://github.com/elastic/beats/issues/25006
