### ISSUE TITLE
Support using a Kibana version from a pull request

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#901]
Same we do for Beats, but from Kibana. We will need:

- monitor Kibana PRs, creating the Docker image for the PR, maybe after a GH comment: i.e. `/package`. This command should be available for Elastic employees, only.
- use that Kibana PR's Docker image in the e2e test framework

**Comment by EricDavisX** [comment]
This is directly in support of the Kibana side issue I had logged for this here:
https://github.com/elastic/kibana/issues/69571


Thanks so much Manu for moving it forward.
