### ISSUE TITLE
cli: unable to run basic fleet profile

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#933]
```
⏚ [adam:~/Projects/e2e-testing/cli] master(+27/-1) 3s ± go run main.go run profile fleet
The kibanaConfigPath variable is not set. Defaulting to a blank string.
Creating network "fleet_default" with the default driver
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT)...
8.0.0-SNAPSHOT: Pulling from elasticsearch/elasticsearch
Digest: sha256:a4a1c524ffea6b3718cb261f5f33373028f7c5687f05cca9172f76be15bdad9c
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT
Pulling package-registry (docker.elastic.co/package-registry/distribution:staging)...
staging: Pulling from package-registry/distribution
Digest: sha256:0b7ed7621e14a0803f867fa976f3a973eb140bd9f250ce4f411a9066540da848
Status: Downloaded newer image for docker.elastic.co/package-registry/distribution:staging
Pulling kibana (docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT)...
8.0.0-SNAPSHOT: Pulling from kibana/kibana
Digest: sha256:8c8493885c048551b0813b892ac988651c5c36009773651eb544edfb6a0fb908
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT
Creating fleet_package-registry_1 ...
Creating fleet_elasticsearch_1    ...
Creating fleet_package-registry_1 ... done
Creating fleet_elasticsearch_1    ... done
Creating fleet_kibana_1           ...
Creating fleet_kibana_1           ... error

ERROR: for fleet_kibana_1  Cannot create container for service kibana: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for kibana  Cannot create container for service kibana: create .: volume name is too short, names should be at least two alphanumeric characters
Encountered errors while bringing up the project.
ERRO[0103] Could not run the profile.                    profile=fleet
```

**Comment by mdelapenya** [comment]
The existing profiles are intended to be used by the e2e test suites, which are populating the proper env vars.

But as you see, it could be misleading. A nice solution would be to place the test profiles in the `e2e` directory, hiding them from the CLI part, and then using the new paths when running the test suite profile. Thoughts?

**Comment by adam-stokes** [comment]
> The existing profiles are intended to be used by the e2e test suites, which are populating the proper env vars.
> 
> But as you see, it could be misleading. A nice solution would be to place the test profiles in the `e2e` directory, hiding them from the CLI part, and then using the new paths when running the test suite profile. Thoughts?

I like this approach, from a developer perspective you just assume that whatever is in `~/.op` is runnable without any additional context requirements. I think limiting those which require certain env variables to run should be put in the `e2e` directory like you mentioned and keep anything in `~/.op` as user-defined/runnable profiles where the control is left to the developer to address any requirements to run.

**Comment by adam-stokes** [comment]
What about moving out the `configurations/kibana.config.yml` into `~/.op/compose/profiles/fleet/configurations/kibana.config.yml`. That would allow the developer to run via cli and give them more flexibility in configuring the service?

**Comment by mdelapenya** [comment]
Mmm, I think that would work and will allow hardcoding the path to the config file instead of passing it as a variable. 👍
