### ISSUE TITLE
poll docker api for checking readiness

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#942]
This came out of this PR discussion https://github.com/elastic/e2e-testing/pull/934#pullrequestreview-620101929

The basic idea is to create some additional api calls to docker for verifying things like docker images being loaded and ready prior to tagging.

We can expand on this issue further to figure out what this api would cover

**Comment by kuisathaverat** [comment]
We will assume the binaries are ready to avoid a defensive approach that makes code complex
