### ISSUE TITLE
move elastic-agent configuration into op.workspace

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#955]
elastic-agent service utilizes a configuration downloaded from github at the time of deployment. We probably need to move this into the packed binary so that it can be referenced by the docker-compose file like the other profiles

ref #944

**Comment by mdelapenya** [comment]
Mmm... I like the approach we are taking moving config files next to the compose files in the CLI. Maybe we can move those files too, and if we detect a PR, override that file at CI. The bad part is that, if a developer wants to do as the CI for a PR locally, we probably will override the config file in the local worspace (~/.op). What are your thoughts on that?
