### ISSUE TITLE
work towards a standard project layout for go

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#959]
I believe a lot of go projects nowadays work towards some kind of standard layout and it seems like this is the one most projects reference https://github.com/golang-standards/project-layout

Should we start thinking about slowly migrating this project to that layout?

**Comment by mdelapenya** [comment]
Yeah, it could be great, although. We could use this issue as `meta` issue to track all refactors needed, linking to each baby step refactor (in new issue each). That way we could prioritise the work with our workloads.

**Comment by adam-stokes** [comment]
This is now fixed in #1008
