### ISSUE TITLE
Consolidate the build system for cli and e2e in the new layout

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#960]
Now that #954 is in place, we'd need to consolidate the build system: Makefiles and NOTICE process 

_Originally posted by @mdelapenya in https://github.com/elastic/e2e-testing/issues/954#issuecomment-809672923_

**Comment by adam-stokes** [comment]
I think with the addition of #977 and #980 this issue is getting pretty close to finished. @mdelapenya what else do we need here?
